### ISSUE TITLE
Hello - How to Start

### ISSUE THREAD

**Issue by rasadeyan** [MrRoundRobin/telegram.bot#1]
Api TelApi = new Api("101860982:AAF4dszej2cJ9rzElp-lmVPuua-hC51t8n4");

        private async void BtnStart_Click(object sender, RoutedEventArgs e)
        {
            try
            {
                Telegram.Bot.Types.User UserMe = await TelApi.GetMe();
                MessageBox.Show(UserMe.FirstName);
            }
            catch (Exception EX)
            {
                MessageBox.Show(EX.Message);
            }
        }

Some one Help me to solve the problem !>?
when I run this code Error 502 (Bad GateWay) pops up!
Help please !?

**Comment by MrRoundRobin** [comment]
Oh there is a bug in GetMe...
Fix iis on the way
