### ISSUE TITLE
more sample

### ISSUE THREAD

**Issue by vioir** [MrRoundRobin/telegram.bot#10]
hi , sorry for sending post here , would you please publish more sample of code ?

**Comment by ScottRFrost** [comment]
@vioir - I have a simple implementation of Telegram.Bot up here if you want to check it out: https://github.com/ScottRFrost/TelegramBot

**Comment by imbeat** [comment]
@vioir look at this https://github.com/imbeat/GuidTelegramBot

**Comment by imbananko** [comment]
sorry, but can I get some custom keyboards examples?

**Comment by MrRoundRobin** [comment]
@imbananko updated the examples repo, take a look [here](https://github.com/MrRoundRobin/telegram.bot.examples/blob/master/Telegram.Bot.Examples.Echo/Program.cs#L87-L128)
