### ISSUE TITLE
check the corecct api 

### ISSUE THREAD

**Issue by soheilrt** [MrRoundRobin/telegram.bot#100]
Hi guys.
how can i check entered api is correct?!

**Comment by Milaine** [comment]
What a fucking waste for the 100th issue, you should be ashamed of yourself.

Question to you: Why would you think you've entered the wrong one?
If the example works, you have the right one.

**Comment by soheilrt** [comment]
because i want to make an application that the user input the API manually!

**Comment by Milaine** [comment]
what do you mean by "inputting the API"?
can you give me an example of what you mean or use another language?
Maybe the token?

**Comment by soheilrt** [comment]
i mean i wwant to write an app to get their API that botfather gived and they can manage their bot

**Comment by MrRoundRobin** [comment]
I think you're talking about the token...

so you can try to call getMe, if there is an `ApiRequestException` with `ErrorCode == 401` and `Message == "[Error]: Unauthorized"` the token is invalid
