### ISSUE TITLE
Reading Document IDs (GIFs)?

### ISSUE THREAD

**Issue by Milaine** [MrRoundRobin/telegram.bot#101]
So, I can get image IDs like this:
`var file = await Bot.GetFile(User.Message.Photo.LastOrDefault().FileId);`
But I don't know how I do this with documents, any ideas here?

**Comment by Milaine** [comment]
`var file = await Bot.GetFile(User.Message.Document.FileId);`
Seems to be everything, just no ``.LastOrDefault()`
Can someone tell me what that's good for tho?

**Comment by MrRoundRobin** [comment]
`Message.Photo` is an array, so `LastOrDefault()` gets the last element in the array.
`Document` is only a single Document
