### ISSUE TITLE
NuGet getting error in VS2013 Professional

### ISSUE THREAD

**Issue by ititraymond** [MrRoundRobin/telegram.bot#104]
Hello,

Today I tried to download telegram.bot via nuget. However, error shown below:
-------------------------------------------------------- 
PM> Install-Package Telegram.Bot
Attempting to resolve dependency 'Microsoft.AspNet.WebApi.Client (≥ 5.2.3)'.
Attempting to resolve dependency 'Newtonsoft.Json (≥ 6.0.4)'.
Install-Package : 'Telegram.Bot' already has a dependency defined for 'Microsoft.AspNet.WebApi.Client'.
At line:1 char:1
+ Install-Package Telegram.Bot
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand
-------------------------------------------------------- 
What I tried are:
- change the C# project .netFramework to 4.5.2
- reinstall the package.

Anyone can help me~~~~~?

Thanks.
Raymond

**Comment by soheilrt** [comment]
hi. i have same problem:( there is no one here that can fix this?!

**Comment by dedo1911** [comment]
if you already have "Microsoft.AspNet.WebApi.Client" package installed via NuGet, try to remove it and let NuGet download it again automatically with the telegram.bot package.

**Comment by MrRoundRobin** [comment]
still valid?

**Comment by soheilrt** [comment]
yes...

**Comment by MrRoundRobin** [comment]
if i understand it correct, you need to update nuget: http://blog.nuget.org/20160627/Announcing-NuGet-3.5-Beta-2-and-2.12-RTM.html

**Comment by MrRoundRobin** [comment]
@ititraymond is this still valid?
