### ISSUE TITLE
Problem sending message to groups and super groups

### ISSUE THREAD

**Issue by mahdibg** [MrRoundRobin/telegram.bot#107]
Hi Dears

I have the following problems:

problem1:
1. I've created a group and added robot to it 
2. Bot messages be displayed in the group. (no problem)

problem2:
1. I've created a group and added robot to it, and it upgraded to supergroup  
2-robot does not send any messages to this supergroup  (problem)

problem3:
1. I've created a group
2. Add the robot got
3. the group was upgraded to supergroup  
4. Sometimes messages are displayed in this supergroup . (another problem)

What should I do to solve the above problems?

thanks a lot

**Comment by dedo1911** [comment]
When a group gets upgraded to supergroup, bots get kicked. You have to add the bot again.
Also, depending on your code, you might want to change the chat id where you send the messages (it changes when the group gets upgraded)

**Comment by MrRoundRobin** [comment]
still valid?

**Comment by SonHoJae** [comment]
@mahdibg you save my time
