### ISSUE TITLE
[Error]: PEER_ID_INVALID

### ISSUE THREAD

**Issue by NaderStar** [MrRoundRobin/telegram.bot#109]
hi guys
i got this error since itry sending a message to a user with a chatid

[Error]: PEER_ID_INVALID

what happened to api ?
is a new rule ?

**Comment by Bouki6** [comment]
I'm not pretty sure but this is main API Error and indicates the Entered Telegram User ID is not valid.

**Comment by dedo1911** [comment]
Is it possible that the user never talked to the bot yet (or stopped it) ?

**Comment by MrRoundRobin** [comment]
still valid?
