### ISSUE TITLE
Cant use Sendphoto to send a simple photo

### ISSUE THREAD

**Issue by navidsadeghpour** [MrRoundRobin/telegram.bot#11]
Hi

I'm trying to use Sendphoto method like this : 

sendphoto(123456789,"https://upload.wikimedia.org/wikipedia/commons/8/8f/Hippie-flower_-_Virginia_-_ForestWander.jpg")

but it does not send anything to the user.

thanks

**Comment by MrRoundRobin** [comment]
Hi,

you musst use the method which takes a FileToSend object, an manual download the image.

Somethink like

```c#
var request = WebRequest.Create("https://upload.wikimedia.org/wikipedia/commons/8/8f/Hippie-flower_-_Virginia_-_ForestWander.jpg");

using (var response = request.GetResponse())
{
    var responseStream = response.GetResponseStream();
    var fileToSend = new FileToSend("ForestWander", responseStream);
    await bot.SendPhoto(123456789, fileToSend);
}
```

**Comment by navidsadeghpour** [comment]
thank you very much for your answer. 
another question : 

if I want to read the image from my own computer ? 

like :

sendphoto(123456789,"C:/a.jpg")

??? how ??

**Comment by MrRoundRobin** [comment]
```c#
using (var stream = new FileStream(@"C:\a.jpg", FileMode.Open))
{
    var fileToSend = new FileToSend("a.jpg", stream);
    await bot.SendPhoto(123456789, fileToSend);
}
```
