### ISSUE TITLE
SendPhoto, SendDocument, SendVideo, SendVoice(these founctions dont work)

### ISSUE THREAD

**Issue by mahdibg** [MrRoundRobin/telegram.bot#114]
hi dears

I've written the following code to send the image. But the file will not be sent. what is the problem?

FTS = new FileToSend();
AddressPic = fileAddress;
FTS.Content = System.IO.File.Open(AddressPic, FileMode.Open, FileAccess.Read, FileShare.Read);
FTS.Filename = "FileName";
Bot.SendPhoto(CurrentUser.Message.Chat.Id, FTS);

tahnks

**Comment by EarsKilla** [comment]
yeah! i'm interested too how to send images.

if trying this:
`tgBot.SendPhoto(msgChatId, imgField, "*secret info*", msgId).Wait();`
i getting exception:
> [Error]: Bad Request: File to send must be non-empty
> StackTrace = "   at Telegram.Bot.Api.<SendWebRequest>d__88`1.MoveNext() in C:\\Users\\fgnoi\\Source\\Repos\\telegram.bot\\src\\Telegram.Bot\\Api.cs:line 1080"

**Comment by MrRoundRobin** [comment]
this works for me:

```c#
const string file = @"C: \[...].jpg";

var fileName = file.Split('\\').Last();

using (var fileStream = new FileStream(file, FileMode.Open, FileAccess.Read, FileShare.Read))
{
    var fts = new FileToSend(fileName, fileStream);

    await Bot.SendChatActionAsync(message.Chat.Id, ChatAction.UploadPhoto);

    await Bot.SendPhotoAsync(message.Chat.Id, fts, "Nice Picture");
}
```
