### ISSUE TITLE
The dependency Microsoft.AspNet.WebApi.Client 5.2.3 does not support framework DNXCore, Version=v5.0.

### ISSUE THREAD

**Issue by Neftedollar** [MrRoundRobin/telegram.bot#119]
Hi, 
please, can you tell me, how can i fix this problem? Somebody test it with .NetCore?

**Comment by mhamm1024** [comment]
please fix it and alert me in:
mhamm.1024@gmail.com

**Comment by MrRoundRobin** [comment]
there is a subscribe button you can use to get informed...

**Comment by Neftedollar** [comment]
@MrRoundRobin maybe we can use interface instead of hardcoded WebApi Assembly?

**Comment by MrRoundRobin** [comment]
solved, netstandard assembly isn't unsing `Microsoft.AspNet.WebApi.Client`

**Comment by Neftedollar** [comment]
Thank you!
