### ISSUE TITLE
Can't Get Group Chat Title

### ISSUE THREAD

**Issue by navidsadeghpour** [MrRoundRobin/telegram.bot#12]
Hi

I was wondering that how can I get the group chat title in telegrom.bot

https://core.telegram.org/bots/api#groupchat

thanks

**Comment by MrRoundRobin** [comment]
Can you try this:

```c#
if (update.Message.Chat.GetType() == typeof(GroupChat))
{
    var title = ((GroupChat)update.Message.Chat).Title;
}
```

or

```c#
var chat = update.Message.Chat as GroupChat;
if (chat.Title != null)
{
    var title = chat.title;
}
```

Maybe i could impliment something linke Message.ChatType like the Message.Type
