### ISSUE TITLE
How best way to Close / Disconnect / Logout

### ISSUE THREAD

**Issue by mafaza86** [MrRoundRobin/telegram.bot#124]
Thank you for telegram.bot, it is very helpful.
I have a problem, when the error connect again.

I Start: bot = new Api ("xxx"); bla bla bla
I Stop Bot: bot = null; bla bla bla
I Start Again: bot = new Api ("xxx"); bla bla bla
I get http error 409 (HTTP Error 409 Conflict)

How best to close the bot, and open it again?
Thank you

**Comment by MrRoundRobin** [comment]
maybe this is related to #125 ?
