### ISSUE TITLE
GetUpdates return error: I get Response status code does not indicate success: 409 (Conflict)

### ISSUE THREAD

**Issue by Ramin-Bateni** [MrRoundRobin/telegram.bot#125]
I get `Response status code does not indicate success: 409 (Conflict).` error while i use `GetUpdates`. Why? What is the reason and how can i solve it?
![e100](https://cloud.githubusercontent.com/assets/9051320/14771083/2db70f20-0a95-11e6-8363-04d3dbb2af3d.JPG)

Note: I get correct data from `await Bot.GetMe();`.

**Comment by MrRoundRobin** [comment]
do you have the webhook set?
try removing it with `Bot.SetWebhook();`

I'll Update the exception, to be more clear

**Comment by Ramin-Bateni** [comment]
Yes, @MrRoundRobin thank you for your answer and update the exception. Although i found the problem (`webhook `issue) sooner because i need it at that time.
