### ISSUE TITLE
Problem in telegram bot api and visual studio 2015

### ISSUE THREAD

**Issue by samanatabaki** [MrRoundRobin/telegram.bot#127]
Hi
I wrote a bot using TelegramBot Api installing from Nuget and it is working very well both in inline and message-based. it is 2 days from my decision to make my bot able to search and return music search results for user. But I saw that this version of api is not supporting InlineQueryResultAudio and it is not implemented in this version. So I decided to download api source code and build it. But it is written in visual studio 2015 and my bot application is in visual studio 2013. I migrated my code to new version and after publishing my code to server, all my mvc side and my api is working and returnung json but telegram bot inline mode is completely stopped working and message-base is returning infinite number of replies.

What should I do?

**Comment by MrRoundRobin** [comment]
i hadn't time to test the changes for the 2.0 API, that's why the nuget package isn't up to date with the source. So currently I can't say if it's an issue with your setup or my implementation

**Comment by Fireblade954** [comment]
Im running the latest version, Api 2.0 Commit broke it. But my pull request should fix that. Havent tested all features/commands but basics seem to work. Havnt found any other bugs / crashed yet.
