### ISSUE TITLE
Bot Looping

### ISSUE THREAD

**Issue by GeARCraft1** [MrRoundRobin/telegram.bot#139]
Hi,
I am making a bot for my school project, put it keep repeating things.
I already included the following:
`
if (e.Message.From == bot.GetMe().Result)
            {
                return;
            }
`
But nothing. What should I do?

**Comment by Fireblade954** [comment]
Just check the examples and go from there....

**Comment by GeARCraft1** [comment]
The examples are async and use bot.GetUpdates. I'm trying to use something like in the issue #78.

**Comment by MrRoundRobin** [comment]
`e.Message.From == bot.GetMe().Result` is always `false` since you're only getting messages from users not from 'yourself'

what's the problem with the code in #78

**Comment by GeARCraft1** [comment]
My bot is just calculating the weather and sending infinitely.

**Comment by GeARCraft1** [comment]
Sorry, revoking the token fixed the issue

Thank you,
Gabriel




On Tue, May 3, 2016 at 3:28 PM -0700, "Robin Müller" <notifications@github.com> wrote:





`e.Message.From == bot.GetMe().Result` is always `false` since you're only getting messages from users not from 'yourself'

what's the problem with the code in #78

---
