### ISSUE TITLE
API answerCallbackQuery no notification appears on the device

### ISSUE THREAD

**Issue by hanc2006** [MrRoundRobin/telegram.bot#140]
Hi,
I trying to use this method to send answers to callback queries sent from inline keyboards but no message appears on the device chat (Telegram client 3.8.1 on iOS 9.2). I use Telegram Bot API 9.0.0-beta3

if (update.Type == UpdateType.CallbackQueryUpdate) {
      await bot.AnswerCallbackQuery(update.CallbackQuery.Id, "Operation done!", true);
}

Thank you.

**Comment by MrRoundRobin** [comment]
i dont't own an iphone, but the following code works on windows (0.9.44) and android (3.8.0):

```c#
        private static readonly Api Bot = new Api("<Key>");
        static void Main(string[] args)
        {
            Bot.CallbackQueryReceived += BotOnCallbackQueryReceived;
            Bot.MessageReceived += BotOnMessageReceived;

            var me = Bot.GetMe().Result;

            Console.Title = me.Username;

            Bot.StartReceiving();
            Console.ReadLine();
            Bot.StopReceiving();
        }

        private static void BotOnMessageReceived(object sender, MessageEventArgs messageEventArgs)
        {
            Bot.SendTextMessage(messageEventArgs.Message.Chat.Id, "OK?", replyMarkup: new InlineKeyboardMarkup(new [] {new InlineKeyboardButton("Test") }));
        }

        private static void BotOnCallbackQueryReceived(object sender, CallbackQueryEventArgs callbackQueryEventArgs)
        {
            Bot.AnswerCallbackQuery(callbackQueryEventArgs.CallbackQuery.Id, "Test", true);
        }
```

**Comment by hanc2006** [comment]
Is strange. I run your code but same behavior . I tried to use an Android phone but I do not receive notifications. I need change some configuration in my bot? I enabled /setoninline

(https://cloud.githubusercontent.com/assets/4517251/15000415/03c720fe-1190-11e6-9885-130eca9b431d.png)

No notification like this.

**Comment by MrRoundRobin** [comment]
@hanc2006 Oh yes, did you set /setinlinefeedback ?

**Comment by hanc2006** [comment]
I set now! /setinlinefeedback and /setoninline activated. But same behavior :(
The changes on my bot take effect immediately or take time?

**Comment by MrRoundRobin** [comment]
can you set an break point in `BotOnCallbackQueryReceived()` an see if you receive the callback?

**Comment by hanc2006** [comment]
The callback works. Look this is my CallbackQueryEventArgs callbackQueryEventArgs object

```
{Telegram.Bot.Types.CallbackQuery}
    Data: "Test"
    From: {Telegram.Bot.Types.User}
    Id: "876134807076262474"
    InlineMessageId: null
    Message: {Telegram.Bot.Types.Message}

{Telegram.Bot.Types.Message}
    Audio: null
    Caption: null
    ChannelChatCreated: false
    Chat: {Telegram.Bot.Types.Chat}
    Contact: null
    Date: {03.05.2016 22:52:26 }
    DeleteChatPhoto: false
    Document: null
    Entities: Count = 0
    EntityValues: Count = 0
    ForwardDate: {01.01.0001 00:00:00 }
    ForwardFrom: null
    From: {Telegram.Bot.Types.User}
    GroupChatCreated: false
    LeftChatMember: null
    LeftChatParticipant: null
    Location: null
    MessageId: 185
    MigrateFromChatId: 0
    MigrateToChatId: 0
    NewChatMember: null
    NewChatParticipant: null
    NewChatPhoto: null
    NewChatTitle: null
    Photo: null
    PinnedMessage: null
    ReplyToMessage: null
    Sticker: null
    SupergroupChatCreated: false
    Text: "OK?"
    Type: TextMessage
    Venue: null
    Video: null
    Voice: null

```

**Comment by hanc2006** [comment]
Now with the new API version 9.0.0.0 Notification works!
Client version: Telegram 3.9.1 on iOS 9.3.1
I preferred the old notification style :(

![img_9121](https://cloud.githubusercontent.com/assets/4517251/15376206/d331d248-1d53-11e6-9a1d-7588321a4a86.PNG)
