### ISSUE TITLE
Max length of messages

### ISSUE THREAD

**Issue by jcmag** [MrRoundRobin/telegram.bot#146]
Hi,
Do you know the maximum length of messages we can send?
Sometimes I got "message too long" or "media_caption_too_long" exceptions, and I'd like to trim my messages instead of dealing with exceptions.

**Comment by MrRoundRobin** [comment]
@jcmag Please take a look at the official docs

**Comment by jcmag** [comment]
ah, found it: 4096 characters for text and 200 for caption
:)
