### ISSUE TITLE
Problem with sending files, images, videos and documents

### ISSUE THREAD

**Issue by webiox** [MrRoundRobin/telegram.bot#149]
Hi,
I get "A task was canceled" error when I upload various types of files through bot.SendDocument(...), SendAudio(...), or other sending files options!
It seems that request time is out or something like this.

Update:
I don't have any problem with sending files smaller than  4mb!
Also I'm using Telegram.Bot version 9.0.0

**Comment by MrRoundRobin** [comment]
Hi, have you tried to increasing the upload timeout? `Bot.UploadTimeout` defaults to 1 minute

**Comment by webiox** [comment]
Thanks for your prompt response Robin, I'm gonna try it! 👍

**Comment by D4NTESPARDA** [comment]
Hi
@webiox 
> I'm gonna try it!
did you tried it?? and what was the result?

**Comment by MrRoundRobin** [comment]
@webiox any update?

**Comment by webiox** [comment]
I'm sorry for my delay,
"Bot.UploadTimeout" worked perfectly fine.
thanks @MrRoundRobin!

**Comment by soheilrt** [comment]
@MrRoundRobin hi.
can u give an example for sending file!!!
I tried everything that I know I get nothing!
filesend function does not work and looks like it doesn't exist!!!
not even an error!
