### ISSUE TITLE
Message.cs

### ISSUE THREAD

**Issue by n0ise9914** [MrRoundRobin/telegram.bot#15]
when you dont make new object of properties inside Message.cs
when we recive message that doesent have replay from, we get error, like
 public User From; that should change to =>  public User From = new User();
getters with type object should refer to another private object in class
or should get new theirselves.

i got error that object not set to instant object many times, event when you check for null you recive error
making new object of objects inside message.cs fixed problem !

**Comment by MrRoundRobin** [comment]
According to the [API Docs](https://core.telegram.org/bots/api#message) the fromfield is always filled, so i don't get the problem
