### ISSUE TITLE
.Net 4.6 and Mono

### ISSUE THREAD

**Issue by dedo1911** [MrRoundRobin/telegram.bot#151]
I'm using .Net 4.6 on mono 4.2.3 and everything seems working fine but:
UnixDatetimeConverter.cs

which seems to have problems with row 52:
return DateTimeOffset.FromUnixTimeSeconds(ticks).DateTime;

Exception:
System.MissingMethodException: Method 'DateTimeOffset.FromUnixTimeSeconds' not found.

I've also done a search in Mono source code, and seems that they have just implemented It.
So: this is not a real issue with the Telegram Bot, which is absolutely awesome, just be sure to get the latest Mono as soon as it's out, till then, stick with .Net 4.5 because of this.

**Comment by MrRoundRobin** [comment]
can you upgrade to mono 4.3.2?
acording to [this](https://fossies.org/diffs/mono/4.2.2.30_vs_4.3.2.467/external/referencesource/mscorlib/system/datetimeoffset.cs-diff.html) diff that's the version which introduced `FromUnixTimeSeconds`

**Comment by dedo1911** [comment]
Latest stable is 4.2.3.4 and I'm not allowed to upgrade to an unstable.
Tried on dev enviroment and seems to be working properly. I'll wait for mono to be released as stable.

**Comment by MrRoundRobin** [comment]
improved targeting, so this should work on 4.2.3. Currently can't test on mono but .NET Portability Report says 100% compatibility on mono
