### ISSUE TITLE
EditDate bug

### ISSUE THREAD

**Issue by dsannikov** [MrRoundRobin/telegram.bot#154]
When it comes to update with EditDate. I get the exception:

An exception of type 'Newtonsoft.Json.JsonReaderException' occurred in mscorlib.dll but was not handled in user code

Additional information: Unexpected character encountered while parsing value: 1. Path 'result [0] .callback_query.message.edit_date', line 2, position 379.

I think you forgot
[JsonConverter (typeof (UnixDateTimeConverter))]

in Message.EditDate

**Comment by MrRoundRobin** [comment]
that's right, sorry. i'll upload the new version later
