### ISSUE TITLE
[RFC] Asynchronous methods should end with "Async"

### ISSUE THREAD

**Issue by thoemmi** [MrRoundRobin/telegram.bot#157]
Many methods of `Client` are asynchronous, but their names do not reflect this. [Microsoft says](https://msdn.microsoft.com/en-us/library/mt674882.aspx)
> The following characteristics summarize what makes the previous example an async method.
> * The method signature includes an async modifier.
> * The name of an async method, by convention, ends with an "Async" suffix.
> * ...

I suggest applying this recommendation to *telegram.bot*, and offer to implement this and send you a PR.

My suggestion is:
* renaming all asynchronous methods of `Client`, e.g. `SendTextMessage` will be `SendTextMessageAsync`
* adding the old methods to `Api`, forwarding the call to the new method, and annotating it with a `ObsoleteAttribute`, e.g.

  ```
  [Obsolete("TestApi is deprecated, please use TestApiAsync")]
  public Task<bool> TestApi() => TestApiAsync();
  ```

I think it's a good point in time for the renaming, as you replace `Api` with `Client` with the next release as well, so it's one "Abwasch" :wink: 

If you agree I'd be happy to provide you with a PR.

**Comment by MrRoundRobin** [comment]
Good idea. But I'll have no time for this until next week. You can create a pull request if you wish.

**Comment by thoemmi** [comment]
OK, I'll do so.

**Comment by MrRoundRobin** [comment]
And maybe `Client` should be `BotClient` or `TelegramBotClient`

**Comment by thoemmi** [comment]
I've created PR #158.

I'm unsure about renaming `Client`, as `Telegram` and `Bot` are both in the namespace already. However, if you think it's a good idea, I'd update my PR to include that renaming too.

**Comment by MrRoundRobin** [comment]
i thought on `HttpClient` (`System.Net.Http.HttpClient`)

my idea was to avoid conflicts with other `Client`s :wink:

**Comment by thoemmi** [comment]
Point taken :wink: 
I've updated the PR accordingly.

**Comment by MrRoundRobin** [comment]
thx for your work on this!
