### ISSUE TITLE
Bot server keeps sending same message

### ISSUE THREAD

**Issue by riskebiz** [MrRoundRobin/telegram.bot#159]
Using webhook, bot server keeps sending same message over and over again.  I deleted webhook but as soon as it was setup again, the messages started like the bot server is in an endless loop.  Is there any way to send command through telegram.bot to delete cache of messages on bot server?

**Comment by MrRoundRobin** [comment]
are you sure, that it's not a problem in your code? if so, please contact [@BotSupport](https://telegram.me/botsupport)

**Comment by riskebiz** [comment]
I don't think my code is the issue.  I've disabled any automatic responses so the hook code only receives and saves the json, and I've also tried changing the location of the webhook to an unrelated service and that location also receives the same messages.  I can see the messages on the server using getupdates when webhook is disabled, and new messages are added to the queue.  It actually looks like it is not the same single message being resent, but rather it is looping though all of the ones on the server, but they are never being cleared even though they are being delivered.  Is there a way I can manually clear these messages using getupdate?  I sent message to bot support but last time it took 11 days for a response, so I'm hoping I'll be able to figure something out on my own.

**Comment by MrRoundRobin** [comment]
ok sorry, didn't understand you correct.

you have to send HTTP status code 200 in response to the request, to mark the messages as received. Is this the case?

**Comment by riskebiz** [comment]
It could be, because I'm not sending that but it's never been an issue until today.  Do you have an example of how this response is sent after receiving json through handler?

**Comment by MrRoundRobin** [comment]
that depends on the framework used to receive the HTTP request

**Comment by riskebiz** [comment]
I'm using StreamReader on an ASHX page like below.  Does this look correct?  I tried it with the context.Response.StatusCode, but the only thing this seems to do is slow down the loop with the responses.  The same messages stay on the server and keep getting redelivered in a continuous loop.

    public void ProcessRequest(HttpContext context)
    {
           var json = new StreamReader(context.Request.InputStream).ReadToEnd();
           context.Response.StatusCode = 200;
           context.Response.StatusDescription = "OK";
           context.Response.Close();**

**Comment by riskebiz** [comment]
I found that if I use GetUpdates with an offset higher than the most recent message on bot server, then it will clear them all.  Not sure why they were accumulating.  The response code did not seem to make a difference and without it messages no longer accumulate.

**Comment by Kannas24** [comment]
I'm having strange issues with getUpdates function

1. Bot API is not returning new message now once I set the offset to some most recent in the chain.
2. Allowed_updates parameter is also not working.
3. callback_query message disappears after 3-4min approx.

**Comment by pouladpld** [comment]
@Kannas24 ask such questions in our tg group. Issues are now only for bug report amd feature proposal.

**Comment by ialexi-bl** [comment]
I consider this issue is still there, because this happened to bot today as well. It was receiving the same update with the exact same date over and over again. I'm absolutely sure my server responded with 200 code, also even if it didn't, isn't telegram supposed to send the update only like a couple of times if my server returns non-200 code?, Because this updates have been received dozens of times and they didn't stop coming. The advice with requesting getUpdates with a non-existent offset worked, but this issue is not nice

**Comment by tuscen** [comment]
Unfortunately we can't do anything about it. This problem is on Telegram. Sometimes their bot servers don't work or work with problems. Today was an outage in Telegram so it might be the cause.
