### ISSUE TITLE
Bot was blocked by the user

### ISSUE THREAD

**Issue by a-a-k** [MrRoundRobin/telegram.bot#164]
`Telegram.Bot.Types.ApiRequestException in mscorlib.dll `
I have sent `/start` command to my bot. In this case my bot must send welcoming message but I got this exception. How it comes? I use 9.0.0 version of NuGet package.
UPD
`10.0.0-beta-3` also crashes.

**Comment by MrRoundRobin** [comment]
The message "Bot was blocked by the user" comes from the telegram servers, so the chat id is wrong, maybe there are old messages in the queue or something?

maybe i can help if you show the code snippet

**Comment by a-a-k** [comment]
```
await Bot.SendChatActionAsync(update.Message.Chat.Id, ChatAction.Typing);
await Bot.SendTextMessageAsync(update.Message.Chat.Id, $"{update.Message.Chat.FirstName}, you are welcome", true, false, 0, Keyboards.MainKeyboard);
```

**Comment by MrRoundRobin** [comment]
what update retrieval method do you use? is the update which is process really the update you think? because if the bot crashes before the update can be confirmed, telegram sends the same update again and again, if this is an old one maybe the bot is indeed blocked by that user. Can you check that?

**Comment by a-a-k** [comment]
I got an error right after I send /start command. I did not have old messages in queue at that moment.
_________________________________________________________________________________
```
private static async Task GettingUpdatesAsync()
.......
updates = await Bot.GetUpdatesAsync(offset);
```

**Comment by MrRoundRobin** [comment]
so, this is a problem outside the scope of the library. you can ping [@BotSupport](https://telegram.me/botsupport)

**Comment by a-a-k** [comment]
After the first message sending and getting error I toggled breakpoints and sow my message in updates. Then I sent some more messages and updates queue grew up. 
After I once used comment 
`  // await Bot.SendTextMessageAsync(update.Message.Chat.Id, $"{update.Message.Chat.FirstName}, you are welcome", true, false, 0, Keyboards.MainKeyboard);`
all updates were confirmed and still works fine.
__________________________________________________________________________________
Thanks, I'll try it.
