### ISSUE TITLE
Incorrect ChatAction

### ISSUE THREAD

**Issue by a-a-k** [MrRoundRobin/telegram.bot#166]
When I send this
`await bot.SendChatActionAsync(update.Message.Chat.Id, ChatAction.FindLocation);`
I need to see somthing like 

> Bot is sending location...

But I see

> Bot is typing text...

Is the problem on the Telegram side?

**Comment by MrRoundRobin** [comment]
created a quick test consle app using the latest beta and it work's for me as expected

```c#
using System;
using Telegram.Bot;
using Telegram.Bot.Types.Enums;

namespace ConsoleApplication
{
    public class Program
    {
        private static readonly TelegramBotClient Bot = new TelegramBotClient("<TOKEN>");

        public static void Main(string[] args)
        {
            Bot.MessageReceived += async (seder, e) => {
                await Bot.SendChatActionAsync(e.Message.Chat.Id, ChatAction.FindLocation);
            };

            Bot.StartReceiving();

            Console.ReadLine();

            Bot.StopReceiving();
        }
    }
}
```

![image](https://cloud.githubusercontent.com/assets/948771/15804683/9f5742c0-2b11-11e6-9880-a15c0761ce29.png)

**Comment by a-a-k** [comment]
> created a quick test consle app using the latest beta and it work's for me as expected
Created it but result was not like yours.
![image](https://cloud.githubusercontent.com/assets/5455861/15804980/66176fc4-2b45-11e6-8fa0-f417345b1db6.png)

**Comment by MrRoundRobin** [comment]
have you tested other clients ? dektop or mobile?

**Comment by a-a-k** [comment]
desktop and android

**Comment by MrRoundRobin** [comment]
okay, looks like this is not implemented in all clients:

- [x] Windows
- [x] OS X
- [ ] Windows Phone
- [ ] Android
- [ ] Web

**Comment by a-a-k** [comment]
Is this your own observations or official info from docs?

**Comment by MrRoundRobin** [comment]
my own

**Comment by a-a-k** [comment]
Thank you for your response
