### ISSUE TITLE
Bot.GetMe() not working when called from a aspx page

### ISSUE THREAD

**Issue by hybrid2102** [MrRoundRobin/telegram.bot#167]
Hello,
when I call Bot.GetMe() from a Test Project it works fine, but when I call it from a code-behind .aspx page it doesn't complete the call.
I have a "core" library project, referenced from both TestProject and WebProject (asp net webforms).
Thanks for the help.

**Comment by MrRoundRobin** [comment]
maybe related to async stuff?

**Comment by hybrid2102** [comment]
Thanks for the quick answer!
You are right, just moved the code in other place - it works fine.
I'll study a better mechanism :-)
