### ISSUE TITLE
Manage supergroup migration

### ISSUE THREAD

**Issue by jcmag** [MrRoundRobin/telegram.bot#171]
Hi,

My bot got this error:
`System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Telegram.Bot.Api.<SendWebRequest>d__89'1.MoveNext()`

the responseObject containing:
`Bad Request: group chat is migrated to a supergroup chat`

So, my bot sent a message to a group that has been migrated to a supergroup. It seems in this case that the ChatId changes.
Also, there is a MigrateToChatId property on a Message object. But how can I retrieve it, since I can't send messages to the group anymore? (so I can't get a Message object)

**Comment by MrRoundRobin** [comment]
if a chat is migrated, there will be two updates `update.Type == UpdateType.MessageUpdate && update.message.Type == MessageType.ServiceMessage` the first update contains [`Update.Message.MigrateFromChatId`](https://mrroundrobin.github.io/telegram.bot/html/P_Telegram_Bot_Types_Message_MigrateFromChatId.htm) and the second [`Update.Message.MigrateToChatId`](https://mrroundrobin.github.io/telegram.bot/html/P_Telegram_Bot_Types_Message_MigrateToChatId.htm)

so you must handle these updates

**Comment by jcmag** [comment]
ok, I better understand.
But for the chat that has already been migrated, I won't receive these updates, right?

**Comment by MrRoundRobin** [comment]
right, these updates are sent once as part of the migration process

**Comment by jcmag** [comment]
ok, thanks!
