### ISSUE TITLE
Custom Dynamic Keyboard

### ISSUE THREAD

**Issue by sorenaa** [MrRoundRobin/telegram.bot#172]
Hi, 
I have some command in my BOT (look like bellow sample), how can define custom keyboard? 
(I need a keyboard with 4 row, each button in a row)
please help me :)

Sample:
/start
   /GetNext
   /Status
   /DayInfo
   /Help

**Comment by MrRoundRobin** [comment]
see [this comment](https://github.com/MrRoundRobin/telegram.bot/issues/128#issuecomment-215790426)

**Comment by sorenaa** [comment]
@MrRoundRobin thanxxxxx

**Comment by MrRoundRobin** [comment]
`using Telegram.Bot.Types`?

**Comment by sorenaa** [comment]
yah!

**Comment by sorenaa** [comment]
Solved. "KeyboardButton[]" changed to "string[]" and worked fine!

**Comment by ahmadaghazadeh** [comment]
```
var rkm = new ReplyKeyboardMarkup();
var rows = new List<KeyboardButton[]>();
var cols = new List<KeyboardButton>();
for (var Index = 1; Index < 17; Index++)
{
    cols.Add(new KeyboardButton("" + Index));
    if (Index%4 != 0) continue;
    rows.Add(cols.ToArray());
    cols = new List<KeyboardButton>();
}
rkm.Keyboard = rows.ToArray();


await botClient.SendTextMessageAsync(
    message.Chat.Id,
    "Choose",
    replyMarkup: rkm);
```

https://stackoverflow.com/a/49364380/1770868
