### ISSUE TITLE
supergroup members

### ISSUE THREAD

**Issue by sinaprog** [MrRoundRobin/telegram.bot#175]
how to get all group or supergroup members as array of user?

**Comment by MrRoundRobin** [comment]
something like this:

```csharp
var administratorMembership = await Bot.GetChatAdministratorsAsync("<chatid>");
var administrators = administratorMembership.Select(a => a.User).ToArray();
```

**Comment by MrRoundRobin** [comment]
ah sorry didn't read correct.
you can't get all users, you can only get how much members a group has and the administrators
