### ISSUE TITLE
Edit Message does not work when using names KeyboardMarkup

### ISSUE THREAD

**Issue by javadmjt** [MrRoundRobin/telegram.bot#176]
im trying to edit a text message.
when send message has a Keyboard Markup edit message don't work.
And the following error occurs

> Bad Request: Message can't be edited

if send message not have keyboardmarkup it works correctly

Thanks

**Comment by MrRoundRobin** [comment]
The [official telegram docs](https://core.telegram.org/bots/api#updating-messages) say

> Please note, that it is currently only possible to edit messages without reply_markup or with inline keyboards.

**Comment by voicerecordist** [comment]
[its maybe help:

](https://core.telegram.org/bots/api#editmessagereplymarkup)
