### ISSUE TITLE
Exception in Api.GetUpdates() method

### ISSUE THREAD

**Issue by sorenaa** [MrRoundRobin/telegram.bot#177]
Api.GetUpdates() throw "Value was either too large or too small for an Int32." Exception.

**Comment by MrRoundRobin** [comment]
is it possible to show the corresponding update json?

**Comment by KozhevnikovDmitry** [comment]
May be Update.Id is larger than Int32? Api.GetUpdates() receives paramenter 'offset', that equals last Update.Id + 1.

**Comment by MrRoundRobin** [comment]
The [docs](https://core.telegram.org/bots/api#available-types) say:
> It is safe to use 32-bit signed integers for storing all Integer fields unless otherwise noted.

that's the case for the [chat id](https://core.telegram.org/bots/api#chat) which is type `long`

**Comment by mhverbakel** [comment]
Is this still an issue? Close the issue otherwise.
