### ISSUE TITLE
Manage 429 errors (too many requests)

### ISSUE THREAD

**Issue by jcmag** [MrRoundRobin/telegram.bot#178]
Hi,
Sometimes my bot sends many notification messages, and it gets 429 errors (Too Many Requests).
To manage that, in SendWebRequest<T> I've added:

`... catch (HttpRequestException e)
  {
      if (e.Message.Contains("429 (Too Many Requests)"))
      {
               Thread.Sleep(10000);
               return await SendWebRequest<T>(method, parameters);
      }
}`

(in my actual code, I also added a limit to the number of retries)
But the bot keeps getting 429 errors, even after several retries; and without having sent other messages...
Am I doing wrong? Or did I miss something?

**Comment by MrRoundRobin** [comment]
have you read the [faq](https://core.telegram.org/bots/faq#my-bot-is-hitting-limits-how-do-i-avoid-this) about this?

**Comment by jcmag** [comment]
I did, but I forgot the limitation for groups :D
I think I'll have to wait 1 minute in that case.
Thanks ;)
