### ISSUE TITLE
Group User Id

### ISSUE THREAD

**Issue by PowerRangerPink** [MrRoundRobin/telegram.bot#179]
How i can get The User Id of a User in a group?

**Comment by MrRoundRobin** [comment]
You can get the admins of a group with [`GetChatAdministratorsAsync`](https://mrroundrobin.github.io/telegram.bot/html/Overload_Telegram_Bot_TelegramBotClient_GetChatAdministratorsAsync.htm).
For the normal users you need to wait for a ServiceMessage with the property [`NewChatMember`](https://mrroundrobin.github.io/telegram.bot/html/P_Telegram_Bot_Types_Message_NewChatMember.htm) or a message from each user but beware of the [privacy mode](https://core.telegram.org/bots/faq#what-messages-will-my-bot-get)

**Comment by PowerRangerPink** [comment]
Thank :)
