### ISSUE TITLE
Error when serializing Update to Json

### ISSUE THREAD

**Issue by mikhail-mikhaylov** [MrRoundRobin/telegram.bot#180]
I need to serialize Update to Json using Json.NET for logging purposes.
But I have an exception when `Update.Message.ForwardDate` is equal to `DateTime.MinValue`, then my attempt to call `JsonConvert.SerializeObject(update)` fails [here ](https://github.com/MrRoundRobin/telegram.bot/blob/74662fb744eef1b973e7fbf7efcb2747b9c3ddc1/src/Telegram.Bot/Converters/UnixDatetimeConverter.cs#L32).

**Comment by MrRoundRobin** [comment]
can you post the exception?

**Comment by mikhail-mikhaylov** [comment]
Not at the moment, but you can easily reproduce it by passing DateTime.MinValue to DateTimeOffset constructor

**Comment by a-stankevich** [comment]
Also exception occurs when serializing Update with Photo. Fixed in #197

**Comment by parabola949** [comment]
I had this issue as well.  Fixed in #215
