### ISSUE TITLE
OAuth authorization

### ISSUE THREAD

**Issue by a-a-k** [MrRoundRobin/telegram.bot#186]
How to implement this with Telegram.Bot?

**Comment by MrRoundRobin** [comment]
i think this is beyond the scope of this issue tracker ;) i suggest you to ask such question on stackoverflow or something

**Comment by eaba** [comment]
@a-a-k Tell use your use case. OAuth Authorize your bot?

**Comment by a-a-k** [comment]
My bot need to prompt the user for a password and login for binding Telegram account to the account of my online store.

**Comment by eaba** [comment]
Could this be useful to you:https://github.com/IdentityServer/IdentityServer3? 
Once you understand how it works, it is easy to setup your bot for oauth authorization

**Comment by a-a-k** [comment]
@eaba thanks
