### ISSUE TITLE
Bad request: Can't find field "message_text"

### ISSUE THREAD

**Issue by javadmjt** [MrRoundRobin/telegram.bot#188]
When using AnswerInlineQuery. Error Can not find field "message_text" happen.
There is no field named message_text in InlineQueryResultArticle to set

what should i do

                InlineQuery query = update.InlineQuery;
                if (query != null)
                {
                    InlineQueryResult[] results = new InlineQueryResult[1];
                    InlineQueryResultArticle result = new InlineQueryResultArticle();
                    var myId = "123";
                    result.Title = "test";
                    result.Id = myId;
                    results[0] = result;
                 
                    await Bot.AnswerInlineQuery(query.Id, results);
                }

**Comment by koroteeww** [comment]
see https://github.com/MrRoundRobin/telegram.bot/issues/182
I just modified InlineQueryResultNew
