### ISSUE TITLE
Send Document

### ISSUE THREAD

**Issue by hanigamini** [MrRoundRobin/telegram.bot#19]
Hi,
How to send file from my computer with SendDocument function  ?

**Comment by sohrablou** [comment]
Hi dear
u can use this code for sending file from local computer:

int chat_id = update.Message.Chat.Id;
int pic_id = 1;  // set picture ID
string path = string.Format(@"D:\pic\{0}.jpg", pic_id); // create picture path in local

if (File.Exists(path))
{
	Types.FileToSend photo = new Types.FileToSend();
	FileStream fs = new FileStream(path, FileMode.Open, FileAccess.Read);
	photo.Filename = fs.Name;
	photo.Content = fs;

	try
	{
		await Bot.SendPhoto(chat_id, photo, "Caption");
	}
	catch (Exception ex)
	{
		Console.WriteLine(ex.HResult + " : " + ex.Message);
	}
}
else
{
	await Bot.SendTextMessage(chat_id, string.Format("I can't find '{0}.jpg' file in computer.", par), false, MsgID); // when i can't find photo in local compute, send comment to user.
}

**Comment by hanigamini** [comment]
Hi,
thanks for your response

**Comment by developerAy** [comment]
Hey there. 
Is there any way to get the posted filestream from the user.
I wanna get audio file and process it.
