### ISSUE TITLE
When i added a bot to group chat, it has stopped working

### ISSUE THREAD

**Issue by mrokiriko** [MrRoundRobin/telegram.bot#190]
I made a simple bot using Echo Example.
It was doing fine untile i added it to group chat.
And my bot just broke after that, he couldn't write messages nor in group chat nor in my one-on-one chat with me.
I change privacy settings for group chats and i reloaded bot multiple times.
Please help, i don't get something.

**Comment by MrRoundRobin** [comment]
do you receive any exception? what version do you use? what environment?

**Comment by mrokiriko** [comment]
I didn't get any exceptions, no errors, everything fine. I made one interesting thing. I deleted my bot and created new one with new token, and it helped: i could talk with him one to one. But when i added him to group, it broke again.
I don't know how to see which version i use and my nuget packet manager just not opening : |
I think problem is in update method or something, but this bug driving me crazy

**Comment by MrRoundRobin** [comment]
can't reproduce... can you post the update json which telegram sends you?

**Comment by mrokiriko** [comment]
well, i reinstalled nuget and found out that i was using Telegram.Bot.7.0.0 i installed 10.3.0
so i rewrote code using new async functions
but i still losing something
![123](https://cloud.githubusercontent.com/assets/20039943/16425279/a80b7252-3d85-11e6-89a8-ef6fbf1756fc.PNG)

**Comment by MrRoundRobin** [comment]
can't see an error in your screenshots

**Comment by mrokiriko** [comment]
no matter what i send to my bot in telegram chat, he don't get it and don't response. and it all began after bot joined in group chat
![123](https://cloud.githubusercontent.com/assets/20039943/16440749/a25931b2-3de6-11e6-8dfe-46d2dc4ed660.PNG)

**Comment by MrRoundRobin** [comment]
looks like the update is no `update.Message.Type == TextMessage`?

i would also suggest that you use [`StartReceiving`](https://mrroundrobin.github.io/telegram.bot/html/Overload_Telegram_Bot_TelegramBotClient_StartReceiving.htm) and the [events](https://mrroundrobin.github.io/telegram.bot/html/Events_T_Telegram_Bot_TelegramBotClient.htm)

**Comment by mrokiriko** [comment]
i checked, message type is right, so there is no mistake.
but i want to try to use StartReceiving and the events. could you send me code examples which use Telegram.Bot.10.3.0?

**Comment by MrRoundRobin** [comment]
updated the [telegram.bot.examples](https://github.com/MrRoundRobin/telegram.bot.examples/blob/master/Telegram.Bot.Examples.Echo/Program.cs#L22-L35) repo

**Comment by mrokiriko** [comment]
you da real mvp.
thank you dude
