### ISSUE TITLE
Problem using with ASP.NET 5

### ISSUE THREAD

**Issue by pnc-matthewgrant** [MrRoundRobin/telegram.bot#191]
Hi,

I've created a simple bot based off of the Echo example provided. This works fine when using the example project as a base, however when ported to an ASP.NET 5 console app it doesn't seem to work.

I'm using version 9.0.0 of the telegram.bot code (I see 10.3.0 has just been released but doesn't seem to be compatible with ASP.NET 5). From capturing the webtraffic it appears that the request and response are being sent correctly but that something is failing internally, possibly while trying to convert the returned JSON into the User model.

![image](https://cloud.githubusercontent.com/assets/9824502/16454970/aa9b3194-3e0a-11e6-837b-75cb954bf4f9.png)

Have you got any idea what may be causing this error or if anything additional is required to get telegram.bot working with ASP.NET 5?

Thanks

**Comment by MrRoundRobin** [comment]
Hello, can you upgrade from dnx to asp.net core? this is what's supported and rtm since a few days, dnx is deprecated

**Comment by mhverbakel** [comment]
A `System.AggregateException` is a wrapper around an exception that occurred in a asynchronous method (like `Run()`). To see what's going wrong, you must click `View detail...` and then check the inner exception. That might give a clue about what is going wrong in your code.

Could you post a screenshot of that inner exception?

**Comment by pnc-matthewgrant** [comment]
Hi, upgrading from dnx to asp.net core did the job when using telegram code 10.3. Thanks for the help.
