### ISSUE TITLE
Bot was blocked by the user

### ISSUE THREAD

**Issue by amirzandi** [MrRoundRobin/telegram.bot#192]
Hi, thank you for your great Bot.

I get an error while a user blocked my robot as follows:

System.AggregateException: One or more errors occurred. ---> Telegram.Bot.Exceptions.ApiRequestException: Bot was blocked by the user

how can I resolve this error?

**Comment by MrRoundRobin** [comment]
you need to use try catch and handle that situation

**Comment by amirzandi** [comment]
Thanks for your reply.

I know how to use try catch but after it enters into the catch block, how can I return it back to my code?

**Comment by MrRoundRobin** [comment]
if it enters the catch block this block will be invoked and after that it resumes after the catch block.

**Comment by amirzandi** [comment]
I have put all the commands in 1 try catch block, you meant that I should just put bot.SendMessageAsync in single try catch block?

**Comment by MrRoundRobin** [comment]
@amirzandi If you need to resume earlier, you must encapsulate fewer statements

**Comment by amirzandi** [comment]
Thanks. I finally put every send command inside a try catch block to get the error code and resolve it.
