### ISSUE TITLE
how edit text of inline message reply markup ؟

### ISSUE THREAD

**Issue by delavarimoshen** [MrRoundRobin/telegram.bot#193]
how edit text of inline message reply markup ؟

e.CallbackQuery.InlineMessageId is null!!! allways

**Comment by MrRoundRobin** [comment]
have you seen this in the [docs](https://core.telegram.org/bots/api#updating-messages)

> Please note, that it is currently only possible to edit messages without reply_markup or with inline keyboards.

also mentioned in #176

**Comment by delavarimoshen** [comment]
thanks
