### ISSUE TITLE
Unable to edit message without inline keyboard.

### ISSUE THREAD

**Issue by mhverbakel** [MrRoundRobin/telegram.bot#195]
### Steps to reproduce
Send a message without an inline keyboard with a text. Immediately after that, update the message to another text, again without an inline keyboard.

### Expected behavior
The message gets changed to the new text.

### Actual behavior
`Bad request: object expected as reply markup`

### Steps to fix
Use the same check for `replyMarkup` as is used for `parseMethod`.

**Comment by MrRoundRobin** [comment]
thanks
