### ISSUE TITLE
get user's phone number after he shared his contact with bot in private chat

### ISSUE THREAD

**Issue by erroe** [MrRoundRobin/telegram.bot#198]
hi
I put keboarbutton for request_contact in my bot.
I want to access to user's phone number after that he shared his contact.
this is my same question and description in stackoverflow: http://stackoverflow.com/questions/38251447/how-can-i-save-users-phone-number-after-he-shared-his-contact
how can I fix this problem?

**Comment by MrRoundRobin** [comment]
If the user presses the [custom keyboard button](https://mrroundrobin.github.io/telegram.bot/html/T_Telegram_Bot_Types_KeyboardButton.htm) with [`RequestContact = true`](https://mrroundrobin.github.io/telegram.bot/html/P_Telegram_Bot_Types_KeyboardButton_RequestContact.htm) you will receive an update with [`Update.Type`](https://mrroundrobin.github.io/telegram.bot/html/P_Telegram_Bot_Types_Update_Type.htm) == [`MessageUpdate`](https://mrroundrobin.github.io/telegram.bot/html/T_Telegram_Bot_Types_Enums_UpdateType.htm) and the contact information in [`Update.Message.Contact`](https://mrroundrobin.github.io/telegram.bot/html/P_Telegram_Bot_Types_Message_Contact.htm)

**Comment by erroe** [comment]
thanks

I try. but I cant use it. I'm a beginner programmer. can you give me a complete short example source code to use this?

**Comment by erroe** [comment]
I have Bot with 2 button. "about us" and "request contact". I use BotOnMessageReceived to Reserved my new message(your example on github) whereas for received request_contact I need to use getUpdates(your above answer). I want to when user select botton "about us", sent some text to him.
```
if (message.Text == ("about us"))
            {
                await Bot.SendTextMessageAsync(message.Chat.Id, "information about us",
                         replyMarkup: keyboard);

            }
```
and when he select button "request contact", sent his phone nubmer to him.

```
static async Task GetContactPhone()
        {
           // var offset = 0;
            
                var Updates = await Bot.GetUpdates();

                foreach (var update in Updates)
                {
                    Console.WriteLine("aaaa");
                    if (update.Type == UpdateType.MessageUpdate)
                    {
                        Console.WriteLine("bbb");
                        var cc = update.Message.Contact.PhoneNumber;
                        //string ph = message.Contact.PhoneNumber;
                        await Bot.SendTextMessageAsync(update.Message.Chat.Id, cc);
                        break;

                    }
                   // offset = update.Id + 1;
                }
           
        }
````

how can I do this(have 2 incoming message.  which one is text message and other one is request_contact, and I want to do proper reaction for them)?
how can I set if statement condition to find "request contact" button when pressed?

**Comment by erroe** [comment]
this is my new code:

`namespace kalayab20bot
{
    class Program
    {
        private static readonly TelegramBotClient Bot = new TelegramBotClient("236497481:AAFyIkkL8kgwOprwPq3M_g0S9Gj7-Qyxq48");
       

        static void Main(string[] args)
        {

           /*Bot.OnMessage += BotOnMessageReceived;
            Bot.OnMessageEdited += BotOnMessageReceived;
            Bot.OnReceiveError += BotOnReceiveError;

            var me = Bot.GetMeAsync().Result;

            Console.Title = me.Username;

            
            
            Bot.StartReceiving();
            Console.ReadLine();

            Bot.StopReceiving();*/

           
            try
            {
                GetContactPhone().Wait();
            }
            catch (AggregateException e)
            {
                throw e.InnerException;
            }
        }


        private static void BotOnReceiveError(object sender, ReceiveErrorEventArgs receiveErrorEventArgs)
        {
            Debugger.Break();
        }


        static async Task GetContactPhone()
        {
            var offset = 0;

            var keyboard = new ReplyKeyboardMarkup(new[]
                {
                    
                    new [] // last row
                    {
                        new KeyboardButton("ارسال شماره تماس")
                         {
                            RequestContact = true
                            
                         }
                    },
                    new [] // first row
                    {
                        new KeyboardButton("درباره ما"),
                        new KeyboardButton("ارتباط با ما"),  
                    }
                    
                    
                });
            int count = 1;
            while (true)
            {
                
                var Updates = await Bot.GetUpdates(offset);


                foreach (var update in Updates)
                {
                    Console.WriteLine("update "+ count.ToString());
                    count++;
                    var message = update.Message;

                  /*  if (message == null || message.Type != MessageType.TextMessage)
                    {
                        return;
                    }

                    */
                    //if (update.Type == UpdateType.MessageUpdate) { }
                  if(update.Type == UpdateType.MessageUpdate)
                  {
                            Console.WriteLine(update.Message.Chat.FirstName + " shared contact");

                            var cc = update.Message.Contact.PhoneNumber;
                            if (cc == null)
                            {
                                cc = "aa";
                            }
                            string ph = message.Contact.PhoneNumber;
                      
                            await Bot.SendTextMessageAsync(update.Message.Chat.Id, cc, replyMarkup: keyboard);
                            //break;
                   }
                 
                  else
                  {       
                    if (message.Text == ("/start"))
                            {
                                Console.WriteLine(update.Message.Chat.FirstName + " start bot");
                                await Bot.SendTextMessageAsync(message.Chat.Id, "با سلام، به کانال رسمی کالایاب خوش آمدید.از این طریق شما عزیزان قادر خواهید بود تا بیش از پیش با گروه کالایاب در ارتباط باشید.\n\nلطفا دکمه -ارسال شماره تماس- را جهت شناسایی فشار دهید. ",
                                         replyMarkup: keyboard);
                               

                            }
                            
                    if (message.Text == ("درباره ما"))
                            {
                                Console.WriteLine(update.Message.Chat.FirstName + " pressed 'about us'");
                                await Bot.SendTextMessageAsync(message.Chat.Id, "با سلام\n\n" + "در سالی که به جهت اقدام و عمل در اقتصاد مقاومتی نامگذاری شده حرکتی بسیار کوچک در جهت معرفی کالاها توسط تولید کنندگان عزیز برداشته ایم.امید که به وظیفه خود عمل کرده باشیم.\n\n",
                                    replyMarkup: keyboard);
                             

                            }
                            
                    if (message.Text == ("ارتباط با ما"))
                            {
                                Console.WriteLine(update.Message.Chat.FirstName + "pressed 'contact us'");
                                await Bot.SendTextMessageAsync(message.Chat.Id, "اطلاعات تماس با گروه کالایاب\n\n" + "شماره ثابت: 021-661 70 431\n\n" + "شماره همراه: 09370855672\n\n" + "فکس: 021-661 70 424\n\n" + "آدرس ایمیل: KalaYab20@Gmail.com\n\n" + "شناسه تلگرام:  @Kalayab20\n\n" + "کانال تلگرام:  @Kalayab20ch\n\n" + "",
                                    replyMarkup: keyboard);

                            }
                  }
                    offset = update.Id + 1;
                }

               
            }
           
        }
    }
}`

and this is result when I run it:
![error](https://cloud.githubusercontent.com/assets/20372106/16894013/83a6d46a-4b5e-11e6-9e03-0b8371cabb81.jpg)

how can fix this problem?

**Comment by erroe** [comment]
I changed my first if statement condition to  if (update.Type == UpdateType.MessageUpdate && message.Type != MessageType.TextMessage). now my bot wroking true.

**Comment by mz1368** [comment]
@MrRoundRobin  I can't  get it in Update.Message.Contact. contact in null again.but when i use locationrequest by the same way is correct and i can get it by update.message.location

**Comment by Olfi01** [comment]
@erroe you need to make sure the message.type of the message you got is MessageType.ContactMessage

**Comment by pouladpld** [comment]
@mz1368 Have a look at this example:

<https://github.com/TelegramBots/telegram.bot/blob/more-tests/test/Telegram.Bot.Tests.Integ/SendingMessages/MessageReplyMarkupTests.cs#L34-L51>
