### ISSUE TITLE
How wait new message from user?

### ISSUE THREAD

**Issue by Radzhab** [MrRoundRobin/telegram.bot#20]
```
if (text == "/weather")
                    {
                       bot.sendText("please type city");
                       var rezult = WaitNewMessage();
                     }
```

**Comment by spoofi** [comment]
Hi.
You need to write separate logic for handling such commands.
For example, remember that user sent the command /weather and after waiting following message from him for the name of the city.

**Comment by sohrablou** [comment]
Hi,
can u send example?
please...

**Comment by spoofi** [comment]
At the moment I  don't have a example.
But now I do experiments with telegram bots and for my case used [this code](https://gist.github.com/spoofi/d6a09ac77543578aa733). In context you can [look for it in file](https://github.com/spoofi/FreudBot/blob/3d677d42f5f5a4ca1b2abb15b73d6fb5b30f3b67/src/Logic/Handlers/UserCommandHandler.cs)
This is a simple command with parameters.

**Comment by sohrablou** [comment]
Hi,
I did not get it.
If possible, set better examples in this regard.

thanks :)

**Comment by spoofi** [comment]
@sohrablou Please specify what kind of example you want?
1. Command with parameters like `/test param1 param2`
2. Or you want an example for command that will work in a mode of dialogue with the user:
`user: /test`
`bot: enter param1`
`user: hello`
`bot: enter param 2`
and etc.

**Comment by furesoft** [comment]
i want the same 2. example

**Comment by warshell** [comment]
> @sohrablou Please specify what kind of example you want?
> 
> 1. Command with parameters like `/test param1 param2`
> 2. Or you want an example for command that will work in a mode of dialogue with the user:
>    `user: /test`
>    `bot: enter param1`
>    `user: hello`
>    `bot: enter param 2`
>    and etc.

im searching for the second exemple
