### ISSUE TITLE
Show a chat message with a bit of delay

### ISSUE THREAD

**Issue by afficionaddo** [MrRoundRobin/telegram.bot#200]
Hi,

### Steps to reproduce
1. Send a hyperlink, it shows the link as a 'Rich Link Preview' after 3-4 seconds.

### Expected  behavior
It should show the hyperlink as a 'Rich Link Preview' without any delay.

### Actual behavior
When I send the hyperlink, it first shows it as text and then takes around 3-4 seconds to generate the 'Rich Link Preview'.

My Issue:    
So can I show the message with a delay so that when it appears in the chat.....it is shown as a 'Rich Link Preview' immediately?

**Comment by mhverbakel** [comment]
This looks like an implementation detail from the telegram client itself. The link previews are generated on the client, so the client causes the delay. You can try this by sending a link to somebody else, and then see how long it takes to show the preview on their device.

Kind regards,

Martijn Verbakel

**Comment by afficionaddo** [comment]
Thanks Martijn for the prompt reply. I will check it out with the above suggestion!

regards.

**Comment by mhverbakel** [comment]
If this indeed answers your question, please close the issue.

Kind regards,

Martijn Verbakel
