### ISSUE TITLE
Application Stoped 

### ISSUE THREAD

**Issue by miladcoder** [MrRoundRobin/telegram.bot#202]
When i start windows form app . and incoming too many message. my app stoped
Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	MyTestBot.exe
  Problem Signature 02:	1.0.0.0
  Problem Signature 03:	578b4562
  Problem Signature 04:	Telegram.Bot
  Problem Signature 05:	10.3.1.0
  Problem Signature 06:	577c400d
  Problem Signature 07:	2fd
  Problem Signature 08:	5a7
  Problem Signature 09:	TH2YEZIPEGVCMVOH3BPXD2RPSLO2UOX2
  OS Version:	6.1.7601.2.1.0.272.7
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

**Comment by mhverbakel** [comment]
Can you provide a screenshot of the exception being thrown? Run the application from Visual Studio (with the debugger attached) and then you should be able to see the exception.

Kind regards,

Martijn Verbakel

**Comment by miladcoder** [comment]
hi dude . this error for Limit Message Text .
solved .
