### ISSUE TITLE
Delete message in supergroups by robot !

### ISSUE THREAD

**Issue by NimaZare** [MrRoundRobin/telegram.bot#203]
Hi sir,
Excuse me, I want to be in the supergroup if a message contains a link has been touted by robots do I clear it.
Is is possible? How do I do this? help me
Thank you

**Comment by mhverbakel** [comment]
Hello,

As far as I know, it is not possible for a bot to remove a message. 

Kind regards,

Martijn Verbakel

**Comment by NimaZare** [comment]
Thank you, sir
But I have seen that if a person was in supergroup message contains the link, the robot removes the message out!
After the robot how to do it do it?!
What is the reason that the robot can't delete messages?
Thanks

**Comment by mhverbakel** [comment]
Hello,

I doubt that this is done by the bot api. I can't find the method to delete messages on the telegram website.

It is probably a robot that directly interacts with the telegram cloud like other client such as the android application, instead of communicating through the bot api. This library is not suitable for that purpose.

Kind regards,

Martijn Verbakel

**Comment by NimaZare** [comment]
Yes, sir, I understand,
I've seen on the Web Telegram
One method is to delete the message, address it is below:

https://core.telegram.org/method/messages.deleteMessages

Do not be too implement this method for API robots?!
Certainly, many people are now in need. Please think about it.
Thanks perfection.

**Comment by mhverbakel** [comment]
Hello,

The method you are referring to is for regular clients, not for bot clients. We can't choose to implement this, because Telegram simply doesn't provide it for bots.

If you want this feature, talk to Telegram support.

Kind regards,
Martijn Verbakel

**Comment by alirezatiptop** [comment]
@NimaZare  salam mohande baraye pak kardane payam tavasote robot be chizi residi ??

**Comment by gilsefidi** [comment]
hey !
with bot you cant delete the messages but if you use special clients like @JiksDev Client you can do anything in your group ...

**Comment by Mahdi-Farhani** [comment]
check this :
https://core.telegram.org/bots/api#deletemessage

**Comment by mohammadyacn314** [comment]
hi !
how can i use deletemessage added to api lib v3.0.0 in java ???
        DeleteMessage delmsg = new DeleteMessage(chat_id, message_id);
can any one help me write a sample example to delete it ???? tnx

my tlg id : @etresib314

**Comment by MrRoundRobin** [comment]
@mohammadyacn314 It's available in the latest beta

**Comment by njsub-zero** [comment]
hi guys.
I have a problem...
I used DeleteMessageAsync(e.Message.Chat.Id, e.Message.MessageId) to delete messages from special ID, but it work only the messages contain TEXT, not media (photo,audio,video,...)
please help me... tnx

**Comment by donc-py** [comment]
> hi guys.
> I have a problem...
> I used DeleteMessageAsync(e.Message.Chat.Id, e.Message.MessageId) to delete messages from special ID, but it work only the messages contain TEXT, not media (photo,audio,video,...)
> please help me... tnx

How do you detect messague wee deleted pls
