### ISSUE TITLE
Broadcast message

### ISSUE THREAD

**Issue by Erffun** [MrRoundRobin/telegram.bot#205]
Hi,
can I broadcast message to all subscribers?

**Comment by MrRoundRobin** [comment]
have you seen [this](https://core.telegram.org/bots/faq#how-can-i-message-all-of-my-bot-39s-subscribers-at-once) FAQ?

**Comment by CristianT** [comment]
As I asked here: http://stackoverflow.com/q/38686587/301198
You can (with the limitations of the API FAQ) but you have to store yourself all the chat ids you ever received and then just send messages to all those chats.

**Comment by Erffun** [comment]
Tanx Cristian

**Comment by Erffun** [comment]
Tanx Cristian
