### ISSUE TITLE
requests in the queue?

### ISSUE THREAD

**Issue by bafekr** [MrRoundRobin/telegram.bot#21]
hi
for example, if 50 requests send from user A, after that run the application, after that send 1 request from user B,when the answer to user B? Probably act program such as queue, if your app acts such as queue and assume each request  needs one second time to answer, so answer to user B after 50 seconds?
is it right?

**Comment by MrRoundRobin** [comment]
hi,
the update processing is part of your application.
you can process the updates in parallel like
```c#
var updates = await Bot.GetUpdates(offset);

Parallel.ForEach(updates, update => {
   DoStuff(update);
});
```

or you can make a web service an register a webhook which is called every time an update comes in (https://core.telegram.org/bots/api#setwebhook)

hope this helps
