### ISSUE TITLE
can't send photo message

### ISSUE THREAD

**Issue by shaheed0** [MrRoundRobin/telegram.bot#211]
I used the sample code at this link to send a photo.
with        const string file = @"C:\Users\Th****ech\Documents\Visual Studio 2013\Projects\TelegramAPI\TelegramAPI\img_books_large.png";
https://github.com/MrRoundRobin/telegram.bot.examples/blob/master/Telegram.Bot.Examples.Echo/Program.cs
but always get ApiRequestException 

### Expected  behavior
photo should be sent

### Actual behavior
get ApiRequestException with "request timed out" message

**Comment by D4NTESPARDA** [comment]
Hi
Did you check it?
https://github.com/MrRoundRobin/telegram.bot/issues/149

**Comment by shaheed0** [comment]
thank you, this was helpful.
the problem is because my ISP throttling telegram connection
