### ISSUE TITLE
Ноw to check existence of Telegram User  

### ISSUE THREAD

**Issue by MMaschine** [MrRoundRobin/telegram.bot#218]
Is there any way to check existence of Telegram user with known UserId? Smth like 
"... var user = _client.GetUser(id)
  if (user != null) ... "

**Comment by MrRoundRobin** [comment]
you can use [`GetChatAsync`](https://mrroundrobin.github.io/telegram.bot/html/Overload_Telegram_Bot_TelegramBotClient_GetChatAsync.htm)
