### ISSUE TITLE
Get_Updates function

### ISSUE THREAD

**Issue by sohrablou** [MrRoundRobin/telegram.bot#22]
Hi.
please check this code...
when Get_Updates function is returned empty or when get a error in get url request, function return null.
this code is true??

```
        public async Task<Update[]> GetUpdates(int offset = 0, int limit = 200, int timeout = 0)
        {
            try
            {
                var parameters = new Dictionary<string, object>
                {
                    {"offset", offset},
                    {"limit", limit},
                    {"timeout", timeout}
                };
                return await SendWebRequest<Update[]>("getUpdates", parameters).ConfigureAwait(false);
            }
            catch (Exception ex)
            {
                int err = ex.HResult;
                Update[] up = new Update[0];
                return up;
            }
        }
```

**Comment by NaderStar** [comment]
please explain your goal

**Comment by sohrablou** [comment]
با سلام. 
هدف این هستش که زمانی که دسترسی ما به آدرس دریافت اطلاعات تلگرام قطع میشه بتونیم خطای اون رو مدیریت کنیم. یا مقدار خالی رو برای بازگشت تابع قرار بدیم و اینطوری مانع بروز خطا در سیستم بشیم.
حتی ممکنه ارتباط سرور با اینترنت قطع بشه و این باعث ایجاد خطا میشه.

این کد در خود فایل اصلی هستش : Api.cs
