### ISSUE TITLE
problem with making dynamic inline keyboard

### ISSUE THREAD

**Issue by soheilrt** [MrRoundRobin/telegram.bot#220]
Hi @MrRoundRobin 
I want to make dynamic inline keyboard with this code:

                        var servicetemp= new StreamReader("service.txt");
                        string temp = servicetemp.ReadToEnd();
                        servicetemp.Close();
                        
                        var arrayList = temp.Split('\n');

                        var inlinekey=new InlineKeyboardButton[arrayList.Length][];
                       int index = 0;
                        foreach (var x in arrayList)
                        {
                            InlineKeyboardButton[] inlinebutton = new[]
                            {
                                new InlineKeyboardButton(x),
                            };
                            inlinekey.SetValue(x,index);
                            index++;
                        }
                        var inlinekeyboard=new InlineKeyboardMarkup(iinlekey);
it gave me this error:
Object cannot be stored in an array of this type.

where am I wrong with this code?!

**Comment by thoemmi** [comment]
Instead of 
```
inlinekey.SetValue(x,index);
```
use
```
inlinekey[index] = inlinebutton;
```
