### ISSUE TITLE
Pgination for InlineQueryResult

### ISSUE THREAD

**Issue by MohammadKhani** [MrRoundRobin/telegram.bot#223]
hi 
please help me 😕
i want use inline query for serach base on key word / after fetch reocord from Data base we have 340  record .
when send inline queryResult(InlineQueryResultArticle) to the user i need pagination / but i dont know how to use next offset for pagination (c# language telegram.bot package)

i dont send more than 50 InlineQueryResultArticle.....😕

"First code test"
 i = 340;
                                InlineQueryResult[] result2 = new InlineQueryResult[i];

                                for (int j = 0; j < i; j++)
                                {
                                    result2[j] = new InlineQueryResultArticle()
                                    {
                                        Description = updateItem.InlineQuery.Id.ToString() + "-2-" + j.ToString(),
                                        Id = (Convert.ToInt64(updateItem.InlineQuery.Id) + j + 1).ToString(),
                                        Title = updateItem.InlineQuery.Id.ToString(),
                                        InputMessageContent = new InputTextMessageContent() { DisableWebPagePreview = false, MessageText = @"Message Content Here" + j.ToString(), ParseMode = ParseMode.Default }
                                    };
                                }
                                await bot.AnswerInlineQuery(updateItem.InlineQuery.Id, result2, null, false);

Thanks 🙏

**Comment by MrRoundRobin** [comment]
untested:

```csharp

var resultsPerRequest = 10;

IEnumerable<dataObject> results = MagicFunctionToGetYourResults();

var offset = int.Parse(updateItem.InlineQuery.Offset ?? "0");

var resultsToSend = new List<InlineQueryResult>();

results.Skip(offset).Take(resultsPerRequest).ToList().ForEach(result => {
    resultsToSend.Add(
        new InlineQueryResultArticle
        {
            Description = result.Description,
// TODO: Add other properties
        }
    );
});

var nextOffset = offset + resultsPerRequest > results.Count ? "" : (offset + resultsPerRequest).toString();

await bot.AnswerInlineQuery(updateItem.InlineQuery.Id, resultsToSend.ToArray(), null, false, nextOffset);
```

**Comment by mrz9009** [comment]
Hi there is a simple example for this

**Comment by pouladpld** [comment]
@mrz9009 we don't provide support on github issues anymore. Join our group chat

**Comment by hanigamini** [comment]
@pouladpld  
What is group chat address?
