### ISSUE TITLE
User not found

### ISSUE THREAD

**Issue by sinaprog** [MrRoundRobin/telegram.bot#224]
Hi
my code is 
`
var m = await majorBot.GetChatMember(long.Parse(sta.GetValueByName("gcid")[0]["Value"] as string), update.Message.From.Id);
                    System.Threading.Thread.Sleep(1000);
                    if (m.Status != ChatMemberStatus.Administrator && m.Status != ChatMemberStatus.Creator && m.Status != ChatMemberStatus.Member)
                    {
                        //some code
                    }

`
It works correctly in many case but in few  this bug was occurred  
{"ok":false,"error_code":400,"description":"Bad Request: User not found"}
*NuGet Package Version:* 
10.3.1
*.NET Version:* 
4.0
*IDE:* 
VS2015
*App:*
Desktop

**Comment by MrRoundRobin** [comment]
is it possible that the user `update.Message.From.Id` is not a member of the group?

**Comment by sinaprog** [comment]
I found my my mistake.it returns user not found because user didn't start in majorBot
