### ISSUE TITLE
Request timed out : Send video from external server

### ISSUE THREAD

**Issue by mahdibg** [MrRoundRobin/telegram.bot#225]
I use following code to send video from external  server

```
WebRequest req = HttpWebRequest.Create(fileurl);
req.Timeout = 100 * 60 * 1000;
using (Stream stream = req.GetResponse().GetResponseStream())
   {
   await MyBot.SendVideoAsync(msgText.Message.Chat.Id, new FileToSend(Tempname.mp4, stream),
   0,TempTitle);
   }
```

If the file size is less than 3MB no problem and the file will be sent,but if the file size is greater,  Request timed out  error will be throw.

How do I fix this problem?

**Comment by MrRoundRobin** [comment]
have you tried to increase the `Timeout` on `MyBot`?

**Comment by mahdibg** [comment]
how can i do it?

**Comment by MrRoundRobin** [comment]
Set `My.UploadTimeout`

**Comment by mahdibg** [comment]
thanks a lot

**Comment by MrRoundRobin** [comment]
so this issue can be closed?
