### ISSUE TITLE
Get Id uploaded file 

### ISSUE THREAD

**Issue by mahdibg** [MrRoundRobin/telegram.bot#227]
I have a huge number of video files.
Users send the file name for the my telegram bot and receives file.

Now, I'm uploading the file once for each user request, as a result, the users waiting time is increased.
As far as I know, any file that is uploaded on the server is a ID, how can I   get this ID?
Can I use this ID instead of uploading the file again? can it reduce waiting time?

thanks a lot

I use this code
```
WebRequest req = HttpWebRequest.Create(filepath);
using (Stream stream = req.GetResponse().GetResponseStream())
{
await MyBot.SendVideoAsync(msgText.Message.Chat.Id, new FileToSend(filename, stream),
0,TempTitle);
}
```

**Comment by mahdibg** [comment]
I use this code

WebRequest req = HttpWebRequest.Create(filepath);
using (Stream stream = req.GetResponse().GetResponseStream())
   {
   await MyBot.SendVideoAsync(msgText.Message.Chat.Id, new FileToSend(filename, stream),
   0,TempTitle);
   }

**Comment by MrRoundRobin** [comment]
the `SendVideoAsync` method returns the sent message, so you can get the id out of this message:

```csharp
var message = await MyBot.SendVideoAsync(msgText.Message.Chat.Id, new FileToSend(filename, stream),
0,TempTitle);
var videoId = message.Video.FileId
```

**Comment by pjpjpjpj** [comment]
how can we send audio to the user using a telegram bot. i am using python and telepot. kindly help

**Comment by MihaZupan** [comment]
This is a repository for the c# Telegram bot library.
Ask your question over at the telepot repo: https://github.com/nickoala/telepot

Please don't comment questions on unrelated, old, closed issues
