### ISSUE TITLE
send message to one or some members?

### ISSUE THREAD

**Issue by LionDev514** [MrRoundRobin/telegram.bot#229]
It is possible, for example, are required to send a private data or simply that it is not of interest rather than for  reciver/receivers?

**Comment by MrRoundRobin** [comment]
Sorry don't understand the question. 
Maybe the official docs can help: https://core.telegram.org/bots/api

**Comment by LionDev514** [comment]
It is simple, you can send a message to a user without others to see?

**Comment by LionDev514** [comment]
my english is bad :P

**Comment by CristianT** [comment]
As said, this is a wrapper of the telegram api (https://core.telegram.org/bots/api)
anything that the api can't do, neither can do this library.

The way it basically works is, a user sends a message to your bot, you store the chat id.
Using this chat id you can reply to the user anytime you want.

There are many other functions in the library and in theory a bot is a programmatic way to use telegram so anything you can do with the regular client probably can be done with this one: sending images, videos, create groups...

**Comment by LionDev514** [comment]
I guess, ready all this resolved, thanks to all
