### ISSUE TITLE
send emoji?

### ISSUE THREAD

**Issue by LionDev514** [MrRoundRobin/telegram.bot#232]
if I use ": joy : (no spaces)" the user will get the same
there any way?

**Comment by MrRoundRobin** [comment]
@LionDev514 You need to send the corresponding Unicode char.

**Comment by LionDev514** [comment]
@MrRoundRobin there is a page that contains a list of those?

**Comment by MrRoundRobin** [comment]
@LionDev514 http://unicode.org/emoji/charts/full-emoji-list.html

**Comment by LionDev514** [comment]
Thanks!
