### ISSUE TITLE
get chat history?

### ISSUE THREAD

**Issue by soheilrt** [MrRoundRobin/telegram.bot#233]
Hi, 

how can I get chat history?

**Comment by MrRoundRobin** [comment]
That's not possible, you can read the official docs and what's possible at https://core.telegram.org/bots/api

**Comment by CristianT** [comment]
You have to store the messages in your own storage when they arrive.
It is specially important to store the Chat ID to be able to reply at a later stage.

**Comment by Evertt** [comment]
On [this docs page on core.telegram.org](https://core.telegram.org/method/messages.getMessages) it seems to suggest that there is a method available to get all the messages from a chat.

And it specifically says:
> **Bots can use this method**

So uhm, why do I get a 404 when I try to call `https://api.telegram.org/bot${BOT_TOKEN}/messages.getMessages` ?
