### ISSUE TITLE
CallbackQueryReceived on web api

### ISSUE THREAD

**Issue by mahanamiri** [MrRoundRobin/telegram.bot#235]
hi
How Use the following command on the Web Api 

`  Bot.CallbackQueryReceived += async (sender, e) =>
            {
                await Bot.AnswerCallbackQueryAsync(e.CallbackQuery.Id, "Information");
                await Bot.SendTextMessageAsync(e.CallbackQuery.Message.Chat.Id, e.CallbackQuery.Data);
            };`

on Web Api ( for Webhook )

**Comment by mahanamiri** [comment]
`public async Task<IHttpActionResult> Post(Update update)
{   
if (update.Message.Text != null)
{
var from = update.Message.From;
switch (update.Message.Text)
{
case "/start":
await Bot.SendTextMessage(update.Message.Chat.Id, _Back(), false, false, 0, _CK.Keyboard_Menu());
break;
}
}
return Ok();
}`

**Comment by MrRoundRobin** [comment]
if you configure a webhook you'll receive the updates via this webhook. you have to check the update type manualy with a switch for example

```csharp

public async Task<IHttpActionResult> Post(Update update)
{   


    switch (update.Type)
    {
        case UpdateType.CallbackQueryUpdate:
            await Bot.AnswerCallbackQueryAsync(update.CallbackQuery.Id, "Information");
            break;

        /// ...

```

**Comment by mahanamiri** [comment]
Thank you so much
