### ISSUE TITLE
Chatfuel update

### ISSUE THREAD

**Issue by Hamix** [MrRoundRobin/telegram.bot#238]
hey
Telegram added **Chatfuel** and your lib doesn't  work for who uses this feature
(I made a new bot and didn't add it to Chatfuel so it's okay now. I thought this feature is essential :smile:. so you can fix it to others :+1:  )
I got these errors:
- new token validation
- getUpdate() when webhook is enabled

Thanks for your support

**Comment by MrRoundRobin** [comment]
hi @Hamix,

I cant' find any news from Telegram about Chatfuel.

I don't know how Chatfuel works, but if you have to setup a Webkooks for them you can't use getUpdate(). see the [docs](https://core.telegram.org/bots/api#getupdates): 

> This method will not work if an outgoing webhook is set up
