### ISSUE TITLE
create Game 

### ISSUE THREAD

**Issue by Bouki6** [MrRoundRobin/telegram.bot#241]
Hello.
recently telegram introduce the game API. i tried to create game with my bot. when i click on play button, i receive a callback query object like this:
`"callback_query":{"id":"286121952441033855","from":{"id":1,"first_name":"t","last_name":"t","username":"t"},"inline_message_id":"BAAAAG8aAwBmgvgD11qQi2LrhC8","chat_instance":"-4795036624376389529","game_short_name":"firstGame"}}`

but now i have no idea how can response to this message!!. does any one know how this works?
thanks.

*NuGet Package Version:* (10.4.0)

*.NET Version:* (net461)

*IDE:* (VS2015)

*App:* (Desktop)

**Comment by MrRoundRobin** [comment]
you need to use version 11.0.0-beta-2

**Comment by Bouki6** [comment]
Thank you.
i update it to 11.0.0-beta-2 and call the AnswerCallbackQueryAsync like this:
`                var task = client.AnswerCallbackQueryAsync(id, url: "https://www.gameeapp.com/game/YXu4mYBb");
                var result = task.GetAwaiter().GetResult();
it returns true but it doesn't redirect me to the game page?
do you know where is th problem?`

**Comment by MrRoundRobin** [comment]
i found the stupid bug 🙈 
i'll upload the fix right away
