### ISSUE TITLE
EditMessage and change the replyMarkup type

### ISSUE THREAD

**Issue by greyfader** [MrRoundRobin/telegram.bot#243]
Hello... I'm trying to use the EditMessage to change the **ReplyMarkup** of a specific message from **InlineKeyboardMarkup** to **ForceReply** and vice versa. I've been trying to do it for some time and it continues to produce error. Attached a modified file of telegram.bot.example.echo.

### Steps to reproduce
1. Send "/inline"
2. Send "/forcereply"
3. Send text with the _forced_ reply

### Expected  behavior
1. When "/forcereply" received, previous inline keyboard would be gone
2. When the user sends text within the forced reply, the keyboard can be used again

### Actual behavior
Various Bad Requests
`Inline Keyboard expected`
`object expected as reply markup`

### Environment data
[Program.txt](https://github.com/MrRoundRobin/telegram.bot/files/521666/Program.txt)
PS. I renamed the file extension to .txt so it's upload-able. Originally .cs file

*NuGet Package Version:* 10.4

*.NET Version:* 4.6.2

*IDE:* VS2015

*App:* general

**Comment by MrRoundRobin** [comment]
have you tried [`EditMessageReplyMarkup`](https://mrroundrobin.github.io/telegram.bot/html/Overload_Telegram_Bot_TelegramBotClient_EditMessageReplyMarkupAsync.htm)

i don't know if it works with ForceReply because the [docs](https://core.telegram.org/bots/api#updating-messages) say 

> Please note, that it is currently only possible to edit messages without reply_markup or with inline keyboards.

**Comment by greyfader** [comment]
I can edit message with `InlineKeyboardMarkup` with `EditMessageTextAsync`.

I've tried `EditMessageReplyMarkupAsync`, and still cannot change the InlineKeyboardMarkup to ForceReply. I tried again with `EditMessageTextAsync`, both goes error with error: `Bad Request: Inline Keyboard Expected`

When I try to edit `ForceReply`, it's **always** error: `Bad Request: Message can't be edited`, with all these methods
```
// case 1
await Bot.EditMessageTextAsync(message.From.Id, msgId, text);
//case 2
await Bot.EditMessageTextAsync(message.From.Id, msgId, text, replyMarkup: keyboard);
// case 3
await Bot.EditMessageTextAsync(message.From.Id, msgId, text, replyMarkup: (new ForceReply() { Force = false }));
// case 4
await Bot.EditMessageTextAsync(message.From.Id, msgId, text, replyMarkup: (new ForceReply() { Force = true}));
// case 5
await Bot.EditMessageReplyMarkupAsync(message.From.Id, msgId, replyMarkup: (new ForceReply() { Force = true }));
```

I guess we cannot edit ForceReply for now...

**Comment by MrRoundRobin** [comment]
okay so this is a restriction by the api and i'll close this issue
