### ISSUE TITLE
Menssage receive

### ISSUE THREAD

**Issue by LionDev514** [MrRoundRobin/telegram.bot#246]
The user to send a message, all right
until the same user sends another message and
the bot begins to receive the same message again and again
even though the user has not sent anything

*NuGet Package Version:* (e.g. 10.4.0)

*.NET Version:* (4.6.1)

*IDE:* (VS2015.)

**Comment by MrRoundRobin** [comment]
@LionDev514 How do you receive messages? If you use GetUpdates, du you increase offset?

**Comment by LionDev514** [comment]
@MrRoundRobin I'm using GetUpdates,not increase anything

**Comment by MrRoundRobin** [comment]
@LionDev514 So please read the docs about offset https://core.telegram.org/bots/api#getupdates

**Comment by LionDev514** [comment]
You will have to see my bad connection?
