### ISSUE TITLE
Error message: Forbidden: bot was kicked from the group chat

### ISSUE THREAD

**Issue by systemeintegratedsolutions** [MrRoundRobin/telegram.bot#250]
### Steps to reproduce
1. Add #1 bot to group
2. Send command to group from client to verify that bot receives command
3. Add bot #2 to group
4. Send command to group using username of each bot to verify that each bot receives respective commands
5. Bot #1 send message to group
6. Bot #2 send message to group
7. Remove bot #2
8. Bot #1 sends message to group

Message is delivered, but I receive the following error:
'Forbidden: bot was kicked from the group chat'

### Expected  behavior
no error message expected

### Actual behavior
receive error message, but message is delivered to group

### Environment data
Windows 10 (All updates installed until today 2016/11/02)

*NuGet Package Version:* (e.g. 10.3.0)
10.4.0
*.NET Version:* (e.g. 4.6, Core RTM, Mono, etc.)
.NET 4.6
*IDE:* (e.g. VS2015, VS Code, etc.)
VS 2015 Community
*App:* (e.g. Desktop, iOS, Android, etc.)
Windows forms

**Comment by mhverbakel** [comment]
Hello,

This sounds like a problem with the Telegram Bot API. Please talk to https://telegram.me/BotSupport for help.

Kind regards,
Martijn Verbakel

**Comment by mhverbakel** [comment]
@MrRoundRobin Close?

**Comment by systemeintegratedsolutions** [comment]
Sure. Thanks! 

 


Namaste,

 

Dave Coates

Managing Director

	

Cell

+27 (0) 84 548 0077


Office

+27 (0) 86 589 2622 


Email

 <mailto:dave@systeme.co.za> dave@systeme.co.za


 

 




 

 <http://nmbbusinesschamber.co.za/publications/11>
