### ISSUE TITLE
Problem with sending files in 11.1.0 pre

### ISSUE THREAD

**Issue by webiox** [MrRoundRobin/telegram.bot#266]
I've updated to 11.1.0 pre. 
In this version, when I try to send any kind of files using "SendPhotoAsync()" or so on, I get "File Type not supported" exception and FileToSend.Type is "Unknown".

**Comment by MrRoundRobin** [comment]
do you want to send a file stream or a file by id?

**Comment by webiox** [comment]
File stream I mean.

**Comment by MrRoundRobin** [comment]
How do you create the `FileToSend` object?

if you don't use the constructor maybe you forogt to set the file type manualy.

i'll update the beta, that this is not required in future
