### ISSUE TITLE
Is There a method or a way to get (restore) a Telegram Message object by a message_id from a chat with my bot?

### ISSUE THREAD

**Issue by Ramin-Bateni** [MrRoundRobin/telegram.bot#267]
I have a bot and i have sent some messages to it. On the other hand my bot recorded the received `Mesaage_Ids `in DB. So i have a list of `Messages_Id `for my `Chat_id`.

Now i want **send (not forward)** one of that messages to other `chat_id `by its recorded `Messages_Id ` in DB.
I think i need a filled Message object to use it to perform sending function. Like this:
```
result = await Bot.SendPhotoAsync(Chat_Id, Msg.Photo.FileId, caption: Msg.Caption);
```
_In the above code the `Msg `is the filled `Message` object (usually we get it easily in `GetUpdate` method)_

 **BUT** in my scenario i have just 2 things to restore the target message to a filled Telegram `Message` object again:
1. A `MessageId`
2. A `ChatId`

**I need Something like this:** 
`var Msg = await Bot.GetMessageAsync(Chat_Id, Messages_Id);`

**I need all data of the target message (Photo.FileId,Video.VideoId, Text, Caption,....) and they should be valid data!** 

**Now my question is:** 
Is There a method or a way to get (restore) a **Telegram Message object** by a `Message_id `from a chat with my bot?

### Environment data
*NuGet Package Version:* (10.4.0) | *.NET Version:* (4.5) | *IDE:* (VS2015) |*App:* (Desktop)

**Comment by MrRoundRobin** [comment]
i think there is no such method, try contacting https://telegram.me/botsupport
