### ISSUE TITLE
Audio caption 

### ISSUE THREAD

**Issue by Ramin-Bateni** [MrRoundRobin/telegram.bot#269]
I want send an audio include a caption, this feature is exists in `Telegram Bot API`
![image](https://cloud.githubusercontent.com/assets/9051320/20664221/83eaec56-b56f-11e6-92bb-247185a5945a.png)

### Expected  behavior
So i expect this parameter in `Audio `and `Voice `method.

### Actual behavior
But i can't find it:
![image](https://cloud.githubusercontent.com/assets/9051320/20663978/a0a7d076-b56e-11e6-9806-27e11015e2c3.png)

### Environment data
NuGet Package Version: (10.4.0)

**Comment by MrRoundRobin** [comment]
should be fixed in beta builds
