### ISSUE TITLE
How to get filestream from user sended audio or image files?

### ISSUE THREAD

**Issue by developerAy** [MrRoundRobin/telegram.bot#27]
Hey there. 
Is there any way to get the posted filestream from the user.
I wanna get audio file and process it.

**Comment by MrRoundRobin** [comment]
Currently that's not possible.

**Comment by MrRoundRobin** [comment]
see
https://twitter.com/telegram/status/614468951926509568

**Comment by developerAy** [comment]
Thank you MrRoundRobin.
