### ISSUE TITLE
Sending a text message to everyone.

### ISSUE THREAD

**Issue by zleeoo** [MrRoundRobin/telegram.bot#270]
Hi, 
i'm learning how to create a telegram bot using this library.
I was wondering if there is a way to directly send a message to an user without using the onMessageReceived method.
Thanks.

**Comment by MrRoundRobin** [comment]
you can send messages to channels, groups and direct chats.

if you want to send a message to a group or direct chat, you need to know it's id.
the id is in every update you receive from this chat. so you need to store this id when you receive the first message.

please read the [faq](https://core.telegram.org/bots/faq) and the official [manual](api)

**Comment by zleeoo** [comment]
Ok, thank you!
