### ISSUE TITLE
Reusing HttpClient

### ISSUE THREAD

**Issue by mikhail-mikhaylov** [MrRoundRobin/telegram.bot#281]
Please consider using only one instance of HttpClient at least per TelegramBotClient.
According to various discussions on StackOverflow and many articles - it is good practice to reuse HttpClient. 
For example you can read this answer http://stackoverflow.com/a/22561368
Here is the quote:

> On requests that go over the internet, I have seen a different story. I have seen a 40% perf hit due to having to re-open the request every time.
> 
> I suspect the hit on a HTTPS connection would be even worse.
> 
> My advice is to keep an instance of HttpClient for the lifetime of your application for each distinct API that you connect to.

In our case we have only one api, so probably it makes sense to reuse HttpClient as much as possible.
But maybe I'm wrong.

**Comment by Dolfik1** [comment]
I tested this library with reusing HttpClient and got next results:

SendTextMessageAsync without reusing HttpClient:
00: 00: 00.3019223

SendTextMessageAsync with reusing HttpClient:
00: 00: 00.0847740

Reused HttpClient 3x faster, than not reused. If you test it with simple bot, you will see the difference.
Also you can get more performance with TcpClient or Socket

**Comment by MrRoundRobin** [comment]
okay, I'll change this. 

I'm very bussy at the moment but I'll try next week

**Comment by AndreyPolovodov** [comment]
+1 for this issue. I can't send more than approx 5-6 messages per sec to different recipients with current version of TelegramBotClient on good internet connection. It's too slow....

**Comment by mhverbakel** [comment]
@AndreyPolovodov
1. Telegram will block your bot if you send too many messages per second.
2. You can create requests concurrent, which means that sending 5-6 messages probably indicates a different issue with your design. Please do not discuss this in this issue.

**Comment by AndreyPolovodov** [comment]
@mhverbakel

1. Yes, I know. Telegram will block only more than 30 messages per seconds for different recipients and 1 per seconds to the same recipient.  So, this is not my case - I haven't got any errors, just got limit with 5-6 messages per second for different recipientds in sending thread where nothing more sending. 
2.  Do you mean to make SendTextMessageAsync in parallel on the same instance of TelegramBotClient?  Yes, I can (Im not sure if its supported by current implementation). 
But currently Telegram limits are implicitly restricted even more by library implementation, and I don't think it's good sign. See messages above, it's not only my problem.
