### ISSUE TITLE
How to start chat?

### ISSUE THREAD

**Issue by A-Programmer** [MrRoundRobin/telegram.bot#286]
Hello.
I know with bot.SendMessage() i can send message to a telegram id, but it is for answering some one, i want to start chat with a telegram id.
You know i have a web application that i want to send message if contact us form submitted.

**Comment by matiuspico** [comment]
Hello @A-Programmer 
Telegram bots cannot start chat. The users should start chat and then your bot can answer them.

**Comment by subins2000** [comment]
Can bots communicate with other bots ?

**Comment by MrRoundRobin** [comment]
@subins2000 No

**Comment by onajafi** [comment]
@subins2000 actually they do but not directly, you can add two or more Bots to a group chat and they can communicate with each other in there.

**Comment by matteocontrini** [comment]
@onajafi I don't think so. Bots cannot read messages from other bots.
