### ISSUE TITLE
how to set offset in event handler for OnMessage event?

### ISSUE THREAD

**Issue by mohammadreza-s** [MrRoundRobin/telegram.bot#287]
Hello.
when OnMessage event is raised, i can get all update by the argument of UpdateEventArgs.
now, my question is how to get updates from a specific offset onward?

**Comment by MrRoundRobin** [comment]
that's not possible if you use the webhook method. otherwise you can use the `GetUpdates` method

**Comment by mohammadreza-s** [comment]
i don't use webhook method. so should i  use Infinite loop and GetUpdates method?

**Comment by MrRoundRobin** [comment]
if you don't use webhooks, the events are never raised you have to use the getupdates method in an infinite loop.

**Comment by mohammadreza-s** [comment]
thank you for reply
