### ISSUE TITLE
Multiple Bots Same Webhook

### ISSUE THREAD

**Issue by eaba** [MrRoundRobin/telegram.bot#288]
### Environment data

*NuGet Package Version:* (e.g. 10.3.0)

*.NET Version:* (e.g. 4.6, Core RTM, Mono, etc.)

*IDE:* (e.g. VS2015, VS Code, etc.)

*App:* (e.g. Desktop, iOS, Android, etc.)
Hi,
Can I use same webhook address for multiple bots?
If yes, will the messages received on the address have something, like bot id, to identify which of the bots the message belongs to?

**Comment by MrRoundRobin** [comment]
hi, didn't tried to use a webhook for multiple bots, you can simply try it.

there is no direct bot id in the updates, i would suggest that you add a parameter to the webhook and check this. like "https://api.bot.com/webhook/?bot=a" and "https://api.bot.com/webhook/?bot=b" or something

**Comment by eaba** [comment]
Okay, thats a good starting point.
Thanks!
