### ISSUE TITLE
CONTENT_URL_INVALID to local file

### ISSUE THREAD

**Issue by raastaa1105** [MrRoundRobin/telegram.bot#293]
### Steps to reproduce
so i use this construction to make some stuff:

```
InlineQueryResultVoice[] p = new InlineQueryResultVoice[1];
            p[0] = new InlineQueryResultVoice();
            p[0].Title = "Your voice";
            p[0].Id = "11";
            p[0].Url = "file://127.0.0.1/downloads/1097008955417205768.mp3";
```
to prevent some useless question i tried next constructions:

p[0].Url = "file:///127.0.0.1/downloads/1097008955417205768.mp3";

p[0].Url = "file:///c:/downloads/1097008955417205768.mp3";

p[0].Url = "http://127.0.0.1/downloads/1097008955417205768.mp3";

### Expected  behavior

So i want to send in inline query voice on this address.

### Actual behavior

I have CONTENT_URL_INVALID so when i change url to something like : "https://google.com"
that construction worked but send empty voice file.

Used your last library.

*IDE:* (VS2015)

*App:* (Desktop)

**Comment by mhverbakel** [comment]
Telegram clients should be able to download from that location, which means that it can't be on your computer (unless you expose it to the internet). Contact [BotSupport](https://t.me/botsupport) for more info on this, and please close this issue.
