### ISSUE TITLE
How to download photo

### ISSUE THREAD

**Issue by SeyedAliDehghan** [MrRoundRobin/telegram.bot#295]
hi
i try download file with this code : 
`var fileid = update.Message.Photo.LastOrDefault().FileId;`
`                                 var file = await Bot.GetFileAsync(fileid,null);`
`                                Console.WriteLine(file.FilePath);`
`                                Console.WriteLine(file.FileStream.ToString());`
`                                using (WebClient mywebclient = new WebClient())`
 `           {`
  `              mywebclient.DownloadFile(file.FilePath, "tst.jpg");`
   `         }`
but is not work it
how to download?

**Comment by mhverbakel** [comment]
See https://core.telegram.org/bots/api#file

**Comment by mhverbakel** [comment]
My mistake. You can use `file.FileStream`, which will already contain the downloaded file.

**Comment by mhverbakel** [comment]
@MrRoundRobin tag question; close
