### ISSUE TITLE
how to get bot's username ?

### ISSUE THREAD

**Issue by mohsen69** [MrRoundRobin/telegram.bot#296]
I need to get bot username from incoming message.is it possible?
I can get username for sender user but i need to bot username

**Comment by mhverbakel** [comment]
If you mean from the update, then it's not possible. What are you trying to achieve here?

**Comment by mohsen69** [comment]
I have following code :
`TelegramBotClient Bot = new TelegramBotClient("<token>");`
`Bot.OnMessage += BotOnMessageReceived;`
`Bot.StartReceiving();`
.
.
and this :
`private async void BotOnMessageReceived(object sender, MessageEventArgs messageEventArgs)`
`{`
`}`

**Comment by mohsen69** [comment]
I have following code :
`TelegramBotClient Bot = new TelegramBotClient("<token>");`
`Bot.OnMessage += BotOnMessageReceived;`
`Bot.StartReceiving();`
.
.
and this :
`private async void BotOnMessageReceived(object sender, MessageEventArgs incomingMsg)`
`{`
    ` // here i need to achieve bot username`
     `// can i access bot username due incomingMsg.Message ?`
`}`

is there any way?

**Comment by mhverbakel** [comment]
No, you can use `GetMe` to retrieve your username, but it won't be efficient to do that every time a message comes in.
@MrRoundRobin tag question

**Comment by mohsen69** [comment]
What about token?

**Comment by mhverbakel** [comment]
Call GetMe once, store the result.
