### ISSUE TITLE
Edit message problem

### ISSUE THREAD

**Issue by NickRimmer** [MrRoundRobin/telegram.bot#299]
I sent message with inline keyboard (with SendTextMessageAsync and InlineKeyboardMarkup).
So, when I tried to edit at first time - EditMessageTextAsync (with InlineKeyboardMarkup) method working fine, but when I trying to modify this message at second time I got "Bad Request: message is not modified"

Where is my mistake?

**Comment by NickRimmer** [comment]
Or who can help me? I want make buttons form like menu. Father bot use it when you ask him /mybots

**Comment by zagkk** [comment]
Hello Nick Rimmer. According to Telegram API:

Please note, that it is currently only possible to edit messages without reply_markup or with inline keyboards.

**Comment by amirtvs** [comment]
hi i have same problem
