### ISSUE TITLE
SendPhoto is not working

### ISSUE THREAD

**Issue by NaderStar** [MrRoundRobin/telegram.bot#3]
{"Required property 'result' not found in JSON. Path '', line 1, position 148."}

**Comment by MrRoundRobin** [comment]
Cann you give me more details?
What function is called? Parameters?
Code snippet?

**Comment by NaderStar** [comment]
var myPhoto= File.ReadAllBytes("I:\\TelegramFolder\\zoroofchiPhoto.jpg");
await zoroofchiBot.SendPhoto(update.Message.Chat.Id, myPhoto, "zoroofchi");

**Comment by NaderStar** [comment]
MrRoundRobin :-) ?

**Comment by MrRoundRobin** [comment]
Found the underlining error. Need to figure out how to deal with it ;)

**Comment by NaderStar** [comment]
thanx MrRoundRobin

**Comment by MrRoundRobin** [comment]
the file to be send needs a file name.
i can't get the file name from byte[] so i decided to use a wraper object:

```c#
var stream = new FileStream(@"c:\xy.png", FileMode.Open);
var fileToSend = new FileToSend("Test.png", stream);

await Bot.SendPhoto(update.Message.Chat.Id, fileToSend, update.Message.Text);
```

**Comment by NaderStar** [comment]
oh thanx yay
its a good wraper MrRoundRobin :-)

**Comment by MrRoundRobin** [comment]
Maybe i'll add byte[] getter/setters later

**Comment by AminSarkar** [comment]
hi.how can i sned a photo by uri ?
can anyone help me ?

**Comment by MihaZupan** [comment]
Don't comment on unrelated 3 year old issues!
Read the documentation and see examples https://telegrambots.github.io/book/3/files/upload.html#uploading-by-url
If you read the Readme you'll find more help resources.

**Comment by Developer-313** [comment]
Hi there, 
I have this problem to and i even used this code:
`
FileToSend fts = new FileToSend("test.png", stream);
bot.SendPhoto(123456789,fts); 
`
bot no change.
any idea what to do?

**Comment by tuscen** [comment]
@Developer-313 Hello, please, read messages above. This is a long closed issue for an unsupported version of the library.

**Comment by Developer-313** [comment]
@tuscen I have read them and did anything to fix this problem but no benefit

**Comment by tuscen** [comment]
@Developer-313 You're using version that's long unsupported. Please, upgrade. If there's a bug in the old version it won't be fixed.

**Comment by Developer-313** [comment]
@tuscen I am using the latest version 15.

**Comment by tuscen** [comment]
@Developer-313 Then, please, fill a new bug report with as much information as you can find.

**Comment by Developer-313** [comment]
@tuscen  how to do that?

**Comment by tuscen** [comment]
@Developer-313 Open a new issue, it's already contains a template.
https://help.github.com/en/github/managing-your-work-on-github/creating-an-issue
