### ISSUE TITLE
Why the audio object should have integer title ?!!!!!!!!!! 

### ISSUE THREAD

**Issue by developerAy** [MrRoundRobin/telegram.bot#30]
I send audio with integer title to my robot and it throw exception after calling the getUpdates() method.
So why the voice object should have integer title!!?

**Comment by MrRoundRobin** [comment]
oh, yes... that was stupid :smile: i'll correct this soon

**Comment by developerAy** [comment]
thank u

**Comment by developerAy** [comment]
the performer is int too.
