### ISSUE TITLE
Can this library runs on Ubuntu (asp .net core)?

### ISSUE THREAD

**Issue by LightVolk** [MrRoundRobin/telegram.bot#301]
Can this library runs on Ubuntu (asp .net core)?

**Comment by midianok** [comment]
Yes, it is.
Library is written with .net standart .NETStandard 1.1.
Just run to build your app for Ubuntu:
```
dotnet restore -r ubuntu.16.10-x64
dotnet publish -c release -r ubuntu.16.10-x64
```
where `ubuntu.16.10-x64` is RID — runtime identifier. If you have other distro, just find it in full RID list
https://docs.microsoft.com/en-us/dotnet/articles/core/rid-catalog
