### ISSUE TITLE
why do i receive Exception when i want to set text of InlineKeyboardButton via Text property?

### ISSUE THREAD

**Issue by mohammadreza-s** [MrRoundRobin/telegram.bot#310]
hi
when i want to generate InlineKeyboardMarkup using the following code, every thing is good

            InlineKeyboardButton[][] a = new InlineKeyboardButton[1][];
            InlineKeyboardButton[] b = new InlineKeyboardButton[1];
            InlineKeyboardButton c = new InlineKeyboardButton("test");
            b[0] = c;
            a[0] = b;
            InlineKeyboardMarkup d = new InlineKeyboardMarkup(a);
            await bot.SendTextMessageAsync(message.Chat.Id, "Sample Button", replyMarkup: d);

but when i want to set Text botton via property, i receive Exception "Bad Request: can't parse inline keyboard button: Text buttons are unallowed in the inline keyboard"
what is the reason?

            InlineKeyboardButton[][] a = new InlineKeyboardButton[1][];
            InlineKeyboardButton[] b = new InlineKeyboardButton[1];
            InlineKeyboardButton c = new InlineKeyboardButton();
            c.Text = "test";
            b[0] = c;
            a[0] = b;
            InlineKeyboardMarkup d = new InlineKeyboardMarkup(a);
            await bot.SendTextMessageAsync(message.Chat.Id, "Sample Button", replyMarkup: d);

**Comment by Olfi01** [comment]
Apparently, the constructor with the string automatically sets the callback data, too. For an inline keyboard button you must at least have `Data` or `SwitchInlineQuery` or `CallbackGame` or `SwitchInlineQueryCurrentChat` though.

**Comment by mohammadreza-s** [comment]
it's true. thank you for reply
