### ISSUE TITLE
Parsing html

### ISSUE THREAD

**Issue by DoomAngels** [MrRoundRobin/telegram.bot#313]
I don't know if this is an issue of the library or the server itself but you cannot send a message with this text: "<i> Hello <b>Boss</b> im here</i>" because the bot doesn't receive it. It cannot be cursive and bold at the same time for some reason so, the correct way to get that working would be: "<i>Hello</i> <b>Boss</b> <i> im here</i>"

Can you confirm that this is en telegram issue or is it an library one ?

**Comment by mhverbakel** [comment]
You can verify this yourself by using the http api to try it.

Kind regards,
Martijn Verbakel

**Comment by DoomAngels** [comment]
I have read the telegram info and they say that you cannot have tags inside tags so it's OK it's something that they have set like this, not an api fault
