### ISSUE TITLE
Deserilization exception ( callback payload to CallBackQuery object )

### ISSUE THREAD

**Issue by hamidnabati** [MrRoundRobin/telegram.bot#319]
Hi,
Im Trying to deserialize callback payload into CallBackQuery object.
but im getting this exception: 

Newtonsoft.Json.JsonSerializationException: Required property 'id' not found in JSON. Path ''.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EndProcessProperty(Object newObject, JsonReader reader, JsonObjectContract contract, Int32 initialDepth, JsonProperty property, PropertyPresence presence, Boolean setDefaultValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, 
...

I guess the conflict occurs at root object, there are no Id property no more, it has been changed to update_id.
this is the payloads log i`ve kept:

{"data":{"update_id":123456789,"message":{"message_id":15,"from":{"id":....,"first_name":"....","last_name":".....","username":"....."},"chat":{"id":....,"first_name":".....","last_name":".....","username":".....","type":"private"},"date":1490133489,"text":"/start","entities":[{"type":"bot_command","offset":0,"length":6}]}}

**Comment by mhverbakel** [comment]
You should not deserialize the callback (random data set by you) into a CallbackQuery (dto crafted by Telegram). Could you show some code, or close the issue if it's resolved now?

**Comment by hamidnabati** [comment]
[HttpPost("callback/{token}")]
public async Task CallBack([FromRoute] string token, [FromBody] CallbackQuery callBackQuery)
{
.....
public async Task CallBack([FromRoute] string token, [FromBody] object data)
        {
            var parsed = ((JObject) data).ToObject<CallbackQuery>();

this one doesnt work also

**Comment by hamidnabati** [comment]
i got it, i`ve made mistake, i resolved the issue. thanks for helping :)
