### ISSUE TITLE
Telegram bot API doesnt send any updates

### ISSUE THREAD

**Issue by Bouki6** [MrRoundRobin/telegram.bot#32]
Hello.
i want to receive the updates with telegram web hook. i create a WCF web service with https binding. here is my web service address:
https://telegram.simclub.ir/Telegram/ReceiveTelegramUpdates.svc

my web service only has a one method. here is my web service class:
```c#
[OperationContract]
[WebInvoke(Method = "POST", BodyStyle = WebMessageBodyStyle.Wrapped, UriTemplate = @"/Update")]
[Description("Use This Method To Update The Bot")]
void Update(string update);
```

i received the updates but telegram sends a null string to me!!. i have no idea what is going on. would you please help me?
Thanks.

**Comment by MrRoundRobin** [comment]
could you try something like
```c#
[WebInvoke(Mathod = "POST", BodyStyle = WebMessageBodyStyle.Bare, UriTemplate = @"/Update", RequestFormat = WebMessageFormat.Json)]
void Test(Update update) { }
```

but maybe you need the change the json serializer to json.net which is described [here](http://blogs.msdn.com/b/carlosfigueira/archive/2011/05/03/wcf-extensibility-message-formatters.aspx)

**Comment by Bouki6** [comment]
Thank you dear MrRoundRobin.
i tried your suggestion. it doesn't work.  the problem is i don't get the json string in order to deserilize it. telegram send the null value to me. I'm really confused. do you think sharing the project might help? if you need any thing just ask it.
thank you so mush.

**Comment by MrRoundRobin** [comment]
ok, i'll try it the next days and provide code samples

**Comment by Bouki6** [comment]
Thank you so mush.
i thought it might be help: i try this:
    public void Test(object update)
        {
            string s = JsonConvert.SerializeObject(update);
        }
and the output was this: {}. its looks like telegram sent a null value to me.!!

**Comment by Bouki6** [comment]
you were right. i just create a update class just you said and it works now.
thank you again.
