### ISSUE TITLE
I wanted simply to know the list of correct extensions to send an audio / voice, because if send an unmanaged extension (opus / aac) creates exception

### ISSUE THREAD

**Issue by cosimochellini** [MrRoundRobin/telegram.bot#321]
### Environment data

*NuGet Package Version:* (e.g. 10.3.0)

*.NET Version:* (e.g. 4.6, Core RTM, Mono, etc.)

*IDE:* (e.g. VS2015, VS Code, etc.)

*App:* (e.g. Desktop, iOS, Android, etc.)

**Comment by MrRoundRobin** [comment]
### SendAudio
https://core.telegram.org/bots/api#sendaudio 
> Your audio must be in the .mp3 format.

### SendVoice
https://core.telegram.org/bots/api#sendvoice
> For this to work, your audio must be in an .ogg file encoded with OPUS

**Comment by cosimochellini** [comment]
not all the .ogg OPUS file work, only the native file made with telegram,
the converted file doesn't work

2017-04-19 13:00 GMT+02:00 Robin Müller <notifications@github.com>:
