### ISSUE TITLE
Errors with update NuGet package

### ISSUE THREAD

**Issue by a-a-k** [MrRoundRobin/telegram.bot#324]
### Steps to reproduce
Update NuGet package from 11.1.0-beta-3 to 12.0.0-beta-02.

### Expected  behavior
Working project.

### Actual behavior
48 errors in 2 files such as: "Argument type TelegramBot.Types.ChatId" is not assaignable to parameter type "long"; changed signature of SendTextMessageAsync() method and changed signatures of KeyboardButton and InlineKeyboardButton ctors.

Could you provide release notes for understanding all of the last changes?

### Environment data

*NuGet Package Version:* (12.0.0-beta-02)

*.NET Version:* (4.6)

*IDE:* (VS2015)

*App:* (Desktop)

**Comment by MrRoundRobin** [comment]
you're right. before I'll release a stable version I want to create a Changelog
