### ISSUE TITLE
Dialogue with user

### ISSUE THREAD

**Issue by nickilanjelo** [MrRoundRobin/telegram.bot#326]
How to organize a dialogue with the user, depending on the selected command? For example, if a user enters a command "/weather", the bot asks the name of the city in which it wants to learn it, after which the bot displays the weather in the selected city.

**Comment by ditu65** [comment]
This is also my problem.

**Comment by mhverbakel** [comment]
This is not an issue with the library, this is asking for a system architecture. You should investigate how a stateful application can be built, but it is generally a better idea to create your bot stateless, so you don't lose state when you restart the bot.

In case you really feel like making a stateful application, this is a way to do it: make a (static) dictionary with the user ID as key and some state object as the value. In this state object, you can keep your parameters like the step that the user is at, or previously entered values. Note that this information is lost unless you store it (maybe a database?).

**Comment by ditu65** [comment]
Thanks, mhverbakel.
