### ISSUE TITLE
how to get post view count

### ISSUE THREAD

**Issue by SalehGladius** [MrRoundRobin/telegram.bot#327]
question is clear ...
[samlple image](https://www.adsensor.ir/themes/adsensor_v1/images/telegram/ppv/telegram-ppv.png)

**Comment by MrRoundRobin** [comment]
I think this is not possible

**Comment by mehrdadmmb2** [comment]
you can use multi proxy

**Comment by SalehGladius** [comment]
what is that?

**Comment by mehrdadmmb2** [comment]
you should copy link of post in telegram and can paste url in browser and set proxy on your system ( for example every 5 seceond ). when proxy changed, refresh the browser

**Comment by SalehGladius** [comment]
I think this is a way for increasing post view count!

but I need to get the number of a post displayed!

**Comment by mehrdadmmb2** [comment]
check html codes:
http://uupload.ir/files/zezy_capture.jpg

**Comment by Olfi01** [comment]
You can't get the post view count as of now. Sorry.
