### ISSUE TITLE
DelMsg

### ISSUE THREAD

**Issue by TeleSudo** [MrRoundRobin/telegram.bot#330]
hi now we can Delete Message with API telegram bot 
Which is unofficially unveiled.

https://api.telegram.org/botToken/deletemessage?chat_id=123&message_id=123

Like This Example In Lua Lang

function deletemessage(chat_id, message_id)
  local url = BASE_URL .. '/deletemessage?chat_id=' .. chat_id

  url = url .. '&message_id=' .. message_id

  return sendRequest(url)
end

Please Insert DelMsg Method in Telegram.bot

**Comment by ImoutoChan** [comment]
api returns 
```
{
ok: false,
error_code: 404,
description: "Not Found: method not found"
}
```

Are you sure it exists?
Have you checked it yourself?

**Comment by TeleSudo** [comment]
Yep 
i Test with 
https://github.com/beyondTeam/bdreborn But i run with API TOKEN
And when i lock link or photo pr voice or ... when members send photo or voice or .. message Successfully deleted

**Comment by TeleSudo** [comment]
Yep
i Test with
https://github.com/beyondTeam/bdreborn But i run with API TOKEN
And when i lock link or photo pr voice or ... when members send photo or voice or .. message Successfully

**Comment by mhverbakel** [comment]
Works for me, but I think we should wait for Telegram to expose this functionality before we implement it in the library.

**Comment by shahinesi** [comment]
Telegram bot Not deleted msg Jost edit

**Comment by MrRoundRobin** [comment]
As this is now offical I'll add this as part of the v3.0 changes see #336
