### ISSUE TITLE
how to load Telegram.Bot project in visual studio 2015 and build it?

### ISSUE THREAD

**Issue by mohammadreza-s** [MrRoundRobin/telegram.bot#331]
After downloading Telegram.Bot project source code, when open solution in visual studio 2015, it can not load Telegram.Bot project.
Could you please tell me that, how to load it?

**Comment by ditu65** [comment]
Visual studio 2015 have native support for NuGet package. After you've opened the project go in the solution explorer and right click on the reference icon in the solution tree. From the contestual menu choose the   NuGet management item, the one with a little gift box as icon. From the search box choose Telegram Bot API and install. If necessary install the last version of the .net framework. Compile the project using the compile all command.

**Comment by MrRoundRobin** [comment]
this project uses vs 2017 features in combination winth .net standard / .net core.
I'm not sure if it can be opened in an older vs. but as described by @ditu65 you are able to use the nuget package in vs 2015
