### ISSUE TITLE
Problem with InlineKeyboardMarkup

### ISSUE THREAD

**Issue by sajedmohseni** [MrRoundRobin/telegram.bot#332]
### Steps to reproduce
I used below example and i clicked on button but nothing happened
```
TelegramBotClient Bot = new TelegramBotClient("<Bot Token>");

Bot.OnMessage += async (seder, e) =>
{
    var keyboard = new InlineKeyboardMarkup(
        new InlineKeyboardButton[][]
        {
        // First row
        new [] {
            // First column
            new InlineKeyboardButton("1.1", "Data1"),

            // Second column
            new InlineKeyboardButton("1.2", "Data2")
        },
        // Second row
        new [] {
            // First column
            new InlineKeyboardButton("2.1", "Data3"),

            // Second column
            new InlineKeyboardButton("2.2", "Data4")
        }
        }
    );

    await Bot.SendTextMessageAsync(e.Message.Chat.Id, "tap on the keyboard", replyMarkup: keyboard);
};

Bot.OnCallbackQuery += async (sender, e) =>
{
    await Bot.AnswerCallbackQueryAsync(e.CallbackQuery.Id, $"You have choosen {e.CallbackQuery.Data}");
};

Bot.StartReceiving();
Console.ReadKey();
Bot.StopReceiving();
```

### Expected  behavior
Bot must response to clicked button without any problems

### Actual behavior
When i clicked on the button nothing happened:
![PNG Image](https://cloud.githubusercontent.com/assets/25695091/26001206/df8ff030-3740-11e7-9306-c9836db7ef01.png)

### Environment data

*Telegram.Bot Version:* Latest version

*.NET Version:* 4.5

*IDE:* VS 2017 Enterprise

*App:* Desktop

*OS:* Windows 10 Enterprise

**Comment by ditu65** [comment]
Hi,
You can try this version of the BotOnCallbackQueryReceived procedure:
Bot.OnCallbackQuery += async (sender, e) =>
{
    await Bot.AnswerCallbackQueryAsync(e.CallbackQuery.Id, $"You have choosen {e.CallbackQuery.Data.ToString()}");
};

please note the call to ToString() method;

This is the piece of my code that had worked for me:

     private static async void BotOnCallbackQueryReceived(object sender, CallbackQueryEventArgs callbackQueryEventArgs)
        {
            await Bot.AnswerCallbackQueryAsync(callbackQueryEventArgs.CallbackQuery.Id,
                @"Received " + callbackQueryEventArgs.CallbackQuery.Data.ToString() );
        }

**Comment by sajedmohseni** [comment]
It works, thank you
