### ISSUE TITLE
OK

### ISSUE THREAD

**Issue by shahinesi** [MrRoundRobin/telegram.bot#335]
how to Get Ok ?

For exampel

if (ok== true)
// code
if (error_code == 400)
//

in 
 public async Task<IHttpActionResult> Post(Update msg)
        {

im using webhook

**Comment by MrRoundRobin** [comment]
The check if a request was succesfull is handled bi the library:

https://github.com/MrRoundRobin/telegram.bot/blob/master/src/Telegram.Bot/TelegramBotClient.cs#L1459-L1460
if `ok != true` en exception will be thrown

**Comment by shahinesi** [comment]
This was the method used in your bot?

                responseObject = JsonConvert.DeserializeObject<ApiResponse<T>>(responseString);
I'm JsonConvert Where?

I want the code I use myself and my Get

**Comment by shahinesi** [comment]
I'm OK I know that is true or false

**Comment by shahinesi** [comment]
@MrRoundRobin

**Comment by shahinesi** [comment]
When I manage 500 error occurs and the message I want to send me out

**Comment by MrRoundRobin** [comment]
As I don't understand your English it would be helpful if you post some source code and error messages or exceptions
