### ISSUE TITLE
Implement 3.0 changes

### ISSUE THREAD

**Issue by MrRoundRobin** [MrRoundRobin/telegram.bot#336]
https://core.telegram.org/bots/api-changelog#may-18-2017

# NEW Payment Platform
- [x] Your bot can now accept payments for goods and services via Telegram. 
- [x] Added new kinds of updates, shipping_query and pre_checkout_query, and new types of message content, invoice and successful_payment.
- [x] Added new methods for payments: sendInvoice, answerShippingQuery, and answerPreCheckoutQuery.
- [x] Added a new type of button, the pay button to InlineKeyboardButton.
# NEW Video Messages
- [x] As of Telegram v.4.0, users can send short rounded video messages, using an interface similar to that of voice notes.
- [x] Added the sendVideoNote method, the new field video_note to Message, the fields record_video_note or upload_video_note to sendChatAction.
# NEW Multilingual Bots
- [x] The User object now may have a language_code field that contains the IETF language tag of the user's language.
- [x] Thanks to this, your bot can now offer localized responses to users that speak different languages.
More power to admin bots
- [x] unbanChatMemeber now also works in channels!
- [x] New method deleteMessage that allows the bot to delete its own messages, as well as messages posted by other in groups and channels where the bot is an administrator.
# Minor Changes
- [x] Replaced the field new_chat_member in Message with new_chat_members (the old field will still be available for a while for compatibility purposes).
- [x] Inline keyboards with switch_inline_query and switch_inline_query_current_chat can no longer be sent to channels because they are useless there.
- [x] New fields gif_duration in InlineQueryResultGif and mpeg4_duration in InlineQueryResultMpeg4Gif.

**Comment by sajedmohseni** [comment]
Hi, i wrote delete method, So if u wanna to add to library.. here's the code:


```
        /// <summary>
        /// Use this method to delete a message. A message can only be deleted if it was sent less than 48 hours ago. Any such recently sent outgoing message may be deleted. Additionally, if the bot is an administrator in a group chat, it can delete any message. If the bot is an administrator in a supergroup, it can delete messages from any other user and service messages about people joining or leaving the group (other types of service messages may only be removed by the group creator). In channels, bots can only remove their own messages. Returns True on success.
        /// </summary>
        /// <param name="chatId"><see cref="ChatId"/> Unique identifier for the target chat or username of the target channel (in the format @channelusername)</param>
        /// <param name="messageId">Unique identifier of the message to delete</param>
        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <returns><c>true</c> on success.</returns>
        /// <see href="https://core.telegram.org/bots/api#deletemessage"/>
        public Task<bool> DeleteMessageAsync(ChatId chatId, int messageId,
            CancellationToken cancellationToken = default(CancellationToken))
        {
            var parameters = new Dictionary<string, object>
            {
                {"chat_id", chatId},
                {"message_id", messageId}
            };

            return SendWebRequestAsync<bool>("deleteMessage", parameters, cancellationToken);
        }
```

**Comment by SalehGladius** [comment]
the nuget package didnt update yet! please update that!

**Comment by SalehGladius** [comment]
I cant find 'deleteMessage' function in Telegram.Bot (nuget pkg) version 10.4.0

**Comment by MrRoundRobin** [comment]
The function is available in the beta builds
