### ISSUE TITLE
Forbidden:bot was blocked by the user

### ISSUE THREAD

**Issue by LightVolk** [MrRoundRobin/telegram.bot#337]
### Steps to reproduce
Do nothing. wait request from blocked user (?)

### Expected  behavior
Do not crush

### Actual behavior
Crush
http://tinypic.com/r/ri65qf/9

### Environment data
ubuntu 16.04 64bit , dotnet 1.1 (.net core)

*NuGet Package Version:* (e.g. 10.3.0)
10.4.0
*.NET Version:* (e.g. 4.6, Core RTM, Mono, etc.)
.net core 1.1
*IDE:* (e.g. VS2015, VS Code, etc.)
VS 2017
*App:* (e.g. Desktop, iOS, Android, etc.)
linux console utility

**Comment by MrRoundRobin** [comment]
You can simply catch the exception
