### ISSUE TITLE
Nuget Update

### ISSUE THREAD

**Issue by Olfi01** [MrRoundRobin/telegram.bot#338]
I'm waiting for a fix for the missing channel_post in Update.Type which is already in the code of this git, when will it get to nuget?

**Comment by a-a-k** [comment]
You could use last beta version if so much need.
![kompstarbotservice - microsoft visual studio 2017-05-26 17 03 22](https://cloud.githubusercontent.com/assets/5455861/26490439/6e6de33a-4235-11e7-843f-01112bd43fa5.png)

**Comment by Olfi01** [comment]
okay, thank you!
