### ISSUE TITLE
how to use Force Reply ?

### ISSUE THREAD

**Issue by msngithub** [MrRoundRobin/telegram.bot#34]
hi

i want to force user to enter reply message
i wrote following code , but telegram didn't show reply message keyboard , just show simple message
        string data = new StreamReader(Request.InputStream).ReadToEnd().ToString().Trim();
        Telegram.Bot.Types.Update update = Telegram.Bot.Types.Update.FromString(data);
        Telegram.Bot.Api api = new Telegram.Bot.Api("myapicode");
        api.SendTextMessage(update.Message.From.Id, "test", false, 0, new ForceReply());

is my code right ?

**Comment by MrRoundRobin** [comment]
Try

```c#
Telegram.Bot.Api api = new Telegram.Bot.Api("myapicode");
api.SendTextMessage(update.Message.From.Id, "test", false, 0, (new ForceReply(){Force = true}));
```

**Comment by msngithub** [comment]
tnx dear robin.
