### ISSUE TITLE
injection with webhoock

### ISSUE THREAD

**Issue by PurTahan** [MrRoundRobin/telegram.bot#344]
Hi
By my security test in using `WebHook` , it's possible to send post data to `WebHook Reciver Page` with `non Telegram Server` ([See Rested](https://chrome.google.com/webstore/detail/rested/eelcnbccaccipfolokglfhhmapdchbfg?utm_source=chrome-app-launcher-info-dialog))  and `Telegram.Bot` Not understand!!!

How to increase **Security**?

**Comment by MrRoundRobin** [comment]
https://core.telegram.org/bots/api#setwebhook

If you'd like to make sure that the Webhook request comes from Telegram, we recommend using a secret path in the URL, e.g. https://www.example.com/<token>. Since nobody else knows your bot‘s token, you can be pretty sure it’s us
