### ISSUE TITLE
stop event due to crash bot or stop bot or error

### ISSUE THREAD

**Issue by mohsenns5** [MrRoundRobin/telegram.bot#347]
Hi dear guys

Before everything thanks for the nice project.

There is not an error, but I have two questions and a request:

1- I want to caught the bots when stop due to crash bot or stop bot and then restart they. Is there a solution? Is there an event like "OnStopped"?(When StopReceiving is occurred)

2- How to retrieve the bot token?

Finally I had a request: If there is a possibility, please add "OnStarted" event(when StartReceiving is completed)

Thanks a lot.
### Environment data

*NuGet Package Version:* (e.g. 10.3.0)
NuGet Version: 2.8.50506.491
*.NET Version:* (e.g. 4.6, Core RTM, Mono, etc.)
4.6
*IDE:* (e.g. VS2015, VS Code, etc.)
VS2017
*App:* (e.g. Desktop, iOS, Android, etc.)
Asp.net mvc

**Comment by MrRoundRobin** [comment]
you can always use try / catch around function calls.

if you use `StartReceiving` you can listen for the `OnReceiveError` and `OnReceiveGeneralError` [event](https://github.com/MrRoundRobin/telegram.bot/blob/master/src/Telegram.Bot/TelegramBotClient.cs#L239-L246)
