### ISSUE TITLE
Telegram.Bot.Examples.Echo(InlineKeyboardButton) has error with the latest library on GitHub, Not on NuGet

### ISSUE THREAD

**Issue by GoldenLighter** [MrRoundRobin/telegram.bot#349]
Dear MrRoundRobin,
Really thanks for the library.
I've downloaded your library from github & your three examples.
Echo example has problem with the latest updated library on github.(It seems nugget package is older than github package)
The error is related to these part(s) : 
1-program.cs
```
new[] // first row
                    {
                        new InlineKeyboardButton("1.1"),
                        new InlineKeyboardButton("1.2"),
                    },
                    new[] // second row
                    {
                        new InlineKeyboardButton("2.1"),
                        new InlineKeyboardButton("2.2"),
                    }
```

2-
Telegram.Bot > Types > InlineKeyboardButton.cs

```
 /// <summary>
        /// Initializes a new instance of the <see cref="InlineKeyboardButton"/> class.
        /// </summary>
        /// <param name="text">The text.</param>
        /// <param name="callbackData">The callback data.</param>
        public InlineKeyboardButton(string text, string callbackData) : this(text)
        {
            CallbackData = callbackData;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="InlineKeyboardButton"/> class.
        /// </summary>
        /// <param name="text">Text of the button</param>
        /// <param name="callbackGame"></param>
        public InlineKeyboardButton(string text, CallbackGame callbackGame) : this(text)
        {
            CallbackGame = callbackGame;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="InlineKeyboardButton"/> class.
        /// </summary>
        /// <param name="text">Text of the button</param>
        private InlineKeyboardButton(string text)
        {
            Text = text;
        }
```

Can you explain what is that private method? 
Here is the error after adding new Telegram.Bot from github :  

> Severity	Code	Description	Project	File	Line	Suppression State
> Error	CS0122	'InlineKeyboardButton.InlineKeyboardButton(string)' is inaccessible due to its protection level	Telegram.Bot.Examples.Echo	Y:\Telegram\Telegram Bot Api\MrRoundRobin\Telegram.Bot.Api\Telegram.Bot.Examples.Echo\Program.cs	95	Active
> 
So for removing this error i did some changes like this :   
```
 /// <summary>
        /// Initializes a new instance of the <see cref="InlineKeyboardButton"/> class.
        /// </summary>
        /// <param name="text">The text.</param>
        /// <param name="callbackData">The callback data.</param>
        public InlineKeyboardButton(string text, string callbackData = null) : this(text)
        {
            CallbackData = callbackData;
        }
```

After that all errors disappeared.
Now i have a new error on runtime in this line : 
```
               await Bot.SendTextMessageAsync(message.Chat.Id, "Choose",
                    replyMarkup: keyboard);
```
And here is the error :  

> An exception of type 'Telegram.Bot.Exceptions.ApiRequestException' occurred in mscorlib.dll but was not handled in user code

Please tell what does this error mean & how can fix it?

**Comment by nasserfet** [comment]
hi ,first thing imo you don't want to change the api it self you just use it , and the example it self have runes perfectly for me , would you see what returned after executing 
" await Bot.SendTextMessageAsync(receiver_telegram_id , "message", replyMarkup: keyboard);"

**Comment by GoldenLighter** [comment]
But there are two versions of telegram bot library :
On github (newer one) 
On Nuget (older one)
Examples are using older one and as i had no error too.
But when i replaced dll with new one i got errors.
So i ask the owner of this library please replace examples with new updated library & you will get those mentioned errors.

**Comment by MrRoundRobin** [comment]
please report this error in the coresponding repo https://github.com/MrRoundRobin/telegram.bot.examples
