### ISSUE TITLE
User Interaction 

### ISSUE THREAD

**Issue by MasiJ** [MrRoundRobin/telegram.bot#352]
Mr RoundRobin Really thanks for the library,
i faced with a problem, it is really kind of you if consider it...
i have some KeyboardButton which labeled NAME , FAMILY .... and i ask user to input related information by click keyboard button...after that user click NAME, messageEventArgs.Message.Text change to NAME but when user input his name, messageEventArgs.Message.Text change to "username" and i can not find the user input is related to which KeyboardButton !!!

**Comment by MrRoundRobin** [comment]
you need to creat a logic your self, this library handles only calling the telegram http api ans handling the responses over to your code
