### ISSUE TITLE
Check if SendTextMessageAsync was unsuccessful

### ISSUE THREAD

**Issue by persiandeveloper** [MrRoundRobin/telegram.bot#356]
Hi

I cant find if anyone else already had the issue, so Is there a way to know that SendTextMessageAsync  was successful and user get the message ?

**Comment by MrRoundRobin** [comment]
https://core.telegram.org/bots/api#sendmessage "

On success, the sent Message is returned."

If there is an error, an exception will be thrown

**Comment by persiandeveloper** [comment]
So handling the exception is enough ?
