### ISSUE TITLE
How to store ChatId?

### ISSUE THREAD

**Issue by buldo** [MrRoundRobin/telegram.bot#361]
I have light access rights system in my bot.
Users are stored in database.
What type should I use to store ChatId in the Db? Bigint? Nvarchar?
According Telegram Bot Api specification ChatId is always numeric, isn't it?

**Comment by MrRoundRobin** [comment]
@buldo "This number may be greater than 32 bits and some programming languages may have difficulty/silent defects in interpreting it. But it is smaller than 52 bits, so a signed 64 bit integer or double-precision float type are safe for storing this identifier."

https://core.telegram.org/bots/api#chat

**Comment by buldo** [comment]
@MrRoundRobin yes. But ChatId type has no conversion to long. And also this type has two public constructors, so I can not be share that Identifier field is filled

**Comment by Ramin-Bateni** [comment]
Yes, I have this problem too! During debugging at runtime I see the `Identifier `and `Username `members in `ChatId` but I don't know how should I get the Identifier from ChatId in my codes. I did not find any method or public property to do it by them:

```
    public class ChatId
    {
        public ChatId(long identifier);
        public ChatId(string username);

        public override bool Equals(object obj);
        public override int GetHashCode();
        public override string ToString();

        public static implicit operator ChatId(long identifier);
        public static implicit operator ChatId(string username);
        public static implicit operator string(ChatId chatid);
    }
```
@MrRoundRobin, How we can get the `Identifier `number from `ChatId`?

**Comment by pouladpld** [comment]
Public channels can have chat id of `@MyPublicChannel` and other chats have a numeric value for chat id.

You can use `ToString()` to get the value. If string starts with `@`, it's a public channel id and otherwise assume it is a `long` value.

Here is implementation of `ChatId.ToString()`:
```c#
public static implicit operator string(ChatId chatid) => 
    chatid.Username ?? chatid.Identifier.ToString();
```

For storing them, If you want to cover all possible situations, I would say always use a `VARCHAR(32)` to store both public channel IDs and numeric values in it. This means just dump the value of `ToString()` into that chat_id column.

> I believe maximum possible length for a channel id is 32. You can ignore the leading `@` character.

Alternatively, create a chat_id table with `VARCHAR` and `INT` columns. Only one of these two columns should contain a value for each chat_id record.

**Comment by buldo** [comment]
@pouladpld from Bot Api Documentation https://core.telegram.org/bots/api#chat field "Id" of object "Chat" can be only Integer. So I see no reasons to use slow string to work with Ids.

**Comment by pouladpld** [comment]
@buldo You are right.
Hopefully, this will be resolved by merging PR #362.

**Comment by Ramin-Bateni** [comment]
I think different! In Telegram **all of the users and chats** (channels, groups, supergroups, bots) has an unique Id named Chat_Id (Identifier) and it return an integer (long) **number**. **It is not optional** but **username is optional**. See this:

![image](https://user-images.githubusercontent.com/9051320/27763635-2e1f30d0-5e9c-11e7-9e65-ec071e421fe6.png)

### Then I think the `ChatId `class should has 2 **public** property in the library like this:

```
public long Identifier {get; private set;}
public string Username {get; private set;}
```
-----------------------------------------------------------------------------------------------------
When i get info from Telegram i'm sure it return data with `Chat_Id `(`Identifier`) ,
**So temporarily:** 
I use the following extension class to solve this issue and get Identifier from `ChatId `object in my project:

```
public static class ChatIdExtension 
{
     public static long Identifier(this ChatId chatId)
     {
         return  long.Parse(chatId.ToString());
     }
}
```
And use it like it:
```
message.Chat.Id.Identifier()
```

**Comment by buldo** [comment]
Actually I see no reasons to combine Id and username to one class. 
Also according to documentation for user ID is 32 bit integer while chat ID is 52 bit integer. 
Now I think that user ID should be uint and Chat ID should be long

**Comment by pouladpld** [comment]
When you send messages, you can pass an integer for chat id or a string for public channel id. See <https://core.telegram.org/bots/api#sendmessage>.

We should keep `ChatId` as is in any API request we make. For example:
```c#
// using Implicit Conversion of long to ChatId
await ITelegramBotClient.SendTextMessageAsync(1234, "message");

// using Implicit Conversion of string to ChatId
await ITelegramBotClient.SendTextMessageAsync("@myChannel", "message");
```

But all the responses coming from Telegram, should have `Id` of type `long` in the `Chat` property:
```c#
long chatid = myUpdate.ChannelPost.Chat.Id; // should be of type long
```

**Comment by bathindahelper** [comment]
Where can we fill the chat id in telegram prefs/settings?
