### ISSUE TITLE
User id should be of type long not ChatId

### ISSUE THREAD

**Issue by pouladpld** [MrRoundRobin/telegram.bot#368]
### Steps to reproduce
```c#
var user = new Telegram.Bot.Types.User {
    Id = new ChatId("String is not a user ID")
};
```

### Expected  behavior
Id property of `Telegram.Bot.Types.User` should be `int`(or possibly `long`).
According to [corresponding Telegram API docs](https://core.telegram.org/bots/api#user), user id should be an integer.

### Actual behavior
Id property of `Telegram.Bot.Types.User` is of type `Telegram.Bot.Types.ChatId` which could contain string values!

#### NuGet Package Version
12.0.0-beta-04

#### .NET Version
.NET Core 1.1

#### IDE
VS 2017

**Comment by buldo** [comment]
@pouladpld Chat Id also should be integer.
I already created PR #362 :)
It covers You isssue

**Comment by MrRoundRobin** [comment]
resolved in latest beta
