### ISSUE TITLE
get messageid after sending message

### ISSUE THREAD

**Issue by msngithub** [MrRoundRobin/telegram.bot#37]
hello

when i put following url in my browser , i get messageid in  json response page 
https://api.telegram.org/bot[token]/sendMessage?chat_id=[chatid]&&text=hi

but when i run following code , i can't get message id
System.Threading.Tasks.Task<Telegram.Bot.Types.Message> tMessage = api.SendTextMessage([chatid], "hi");

how can i get messageid ?

with many thanks

**Comment by MrRoundRobin** [comment]
All Methods in this Library ar Async, so you musst use
```c#
var message = await api.SendTextMessage(chatId, "hi");
```
or
```c#
var message = api.SendTextMessage(chatId, "hi").Result;
```

**Comment by rootx-dev** [comment]
"https://api.telegram.org/bot{token}/sendMessage?chat_id={-100XXXXXX}&text=hi"

**Comment by rootx-dev** [comment]
> hello
> 
> when i put following url in my browser , i get messageid in json response page [https://api.telegram.org/bot[token]/sendMessage?chat_id=[chatid]&&text=hi](https://api.telegram.org/bot%5Btoken%5D/sendMessage?chat_id=%5Bchatid%5D&&text=hi)
> 
> but when i run following code , i can't get message id System.Threading.Tasks.Task<Telegram.Bot.Types.Message> tMessage = api.SendTextMessage([chatid], "hi");
> 
> how can i get messageid ?
> 
> with many thanks

](https://api.telegram.org/bot{token}/sendMessage?chat_id={-100XXXXXX}&text=hi)
