### ISSUE TITLE
Update Chat class to newer version

### ISSUE THREAD

**Issue by Ramin-Bateni** [MrRoundRobin/telegram.bot#371]
The current [Chat class](https://github.com/MrRoundRobin/telegram.bot/blob/master/src/Telegram.Bot/Types/Chat.cs) is not update.

It has not some properties while Telegram return the following properties when we fire `getChat `method:

![image](https://user-images.githubusercontent.com/9051320/27764016-bd1be780-5ea4-11e7-86db-0297bb0495d6.png)

Please update [Chat class](https://github.com/MrRoundRobin/telegram.bot/blob/master/src/Telegram.Bot/Types/Chat.cs) and write other related codes.
Thank you...

**Comment by Olfi01** [comment]
of course it isnt, 3.1 update just came out. see #366

**Comment by MrRoundRobin** [comment]
resolved in dcde94b9324fc5002aba79cfa1cf33ff086652a8
