### ISSUE TITLE
nuget package is not updated

### ISSUE THREAD

**Issue by vahidreza** [MrRoundRobin/telegram.bot#380]
hi
I guess the nuget package is not updated (v10.4) based on your latest commits.
for example I have not found anywhere to use DeleteMessageAsync.
am I doing anything wrong or not?
thanks

**Comment by MrRoundRobin** [comment]
should be in the beta, I'll update teh package in a few days when #366 is merged

**Comment by vahidreza** [comment]
thanks I checked  include prerelease and saw version 12
good job
