### ISSUE TITLE
InlineQueryResultGame Not recognized

### ISSUE THREAD

**Issue by dmakhkamov** [MrRoundRobin/telegram.bot#383]
### Steps to reproduce
InlineQueryResultGame  is not recognized as a class.

### Environment data

*NuGet Package Version:* 10.4.0

*.NET Version:* .NET Framework 4.6.2

*IDE:* VS2015

*App:* WEB API

**Comment by dmakhkamov** [comment]
![image](https://user-images.githubusercontent.com/16116474/28119011-6474f53a-6724-11e7-9abb-640dc8e62afb.png)

**Comment by dmakhkamov** [comment]
Issue resolved with pre-release nuget package

**Comment by pouladpld** [comment]
Btw, that type inherits stuff that doesn't really belong to it as per documentations.
