### ISSUE TITLE
webhook self signed certificate

### ISSUE THREAD

**Issue by kamzara** [MrRoundRobin/telegram.bot#384]
### Environment data

*NuGet Package Version:* (e.g. 10.3.0)

*.NET Version:* (e.g. 4.6, Core RTM, Mono, etc.)

*IDE:* (e.g. VS2015, VS Code, etc.)

*App:* (e.g. Desktop, iOS, Android, etc.)

**Comment by MrRoundRobin** [comment]
the issue template is there to be used
