### ISSUE TITLE
autocomplete with bot telegram

### ISSUE THREAD

**Issue by antonioita** [MrRoundRobin/telegram.bot#386]
Hello you can create an autocomplete search with your bot telegram you developed

**Comment by Olfi01** [comment]
maybe you can, but why should this be an issue here?

**Comment by antonioita** [comment]
Sorry but I do not know where to post the question.

**Comment by Olfi01** [comment]
what exactly do you even want?

**Comment by antonioita** [comment]
An example of autocomplete with telegram.bot

**Comment by Olfi01** [comment]
Try asking at [Stackoverflow](http://www.stackoverflow.com) or something, here's not the place for that (IMO)

**Comment by antonioita** [comment]
OK thanks
