### ISSUE TITLE
set webhook example?

### ISSUE THREAD

**Issue by navidsadeghpour** [MrRoundRobin/telegram.bot#39]
Hi,

I'm very new in this telegram things. 
can you help me and make an example for using webhook and certificate parameter?

I just don no how to use webhook in my C# program,
before this certificate parameter I was working with getupdate.

Thanks...

**Comment by MrRoundRobin** [comment]
why do you want to switch to webhooks?

i started to code an example web service but it took longer than i thought currently i have no time to finish it.

**Comment by navidsadeghpour** [comment]
I want webhook because im writing a webservice and i don want those get update and while...  things..

**Comment by navidsadeghpour** [comment]
if  you think that webservice that you are working on can help ,  can you send it to me?

**Comment by ScottRFrost** [comment]
I'd also like to see a ASP.NET Web API example.  

@MrRoundRobin The reason I want to use it is pushing the updates from their server uses less bandwidth and CPU time than constantly pulling every second with my console app.  Plus, it's nice to support both approaches since the bot API offers both.

**Comment by MrRoundRobin** [comment]
I've created an example using OWIN and WebAPI, see 7ceaade58be7f4df9f6f561cbed499c5a8453373

**Comment by blacksagres** [comment]
@ScottRFrost did you get the webhook to work on your side? I've tried following the example on [7ceaade](https://github.com/MrRoundRobin/telegram.bot/commit/7ceaade58be7f4df9f6f561cbed499c5a8453373), but so far I can only reach my Post with REST testing.

@MrRoundRobin I've followed the example using my web application, the code below is on my Application_Start method on the Global.asax.cs. On the Post method in my controller I've done the same thing on your example but no success.

```
void Application_Start(object sender, EventArgs e) {
      // Code that runs on application startup
      AreaRegistration.RegisterAllAreas();
      GlobalConfiguration.Configure(WebApiConfig.Register);
      RouteConfig.RegisterRoutes(RouteTable.Routes);
      // Setting up webhook
      Telegram.Bot.Api bot = new Telegram.Bot.Api("mytoken");
      bot.SetWebhook("https://myhost:8443/api/webhook").Wait();
}
```

If this information is relevant, my application is hosted on godaddy using a self-signed certificate.

**Comment by MrRoundRobin** [comment]
If you use a self-signed certificate you musst upload it:

```c#
var cert = new FileToSend("certificate.cer", new FileStream("path\to\certificate.cer", FileMode.Open));
bot.SetWebhook("https://thecloudmaster.net:8443/hook", cert).Wait();
```

**Comment by blacksagres** [comment]
Still doesn't seem to work.

```javascript
void Application_Start(object sender, EventArgs e) {
      // Code that runs on application startup
      AreaRegistration.RegisterAllAreas();
      GlobalConfiguration.Configure(WebApiConfig.Register);
      RouteConfig.RegisterRoutes(RouteTable.Routes);
      // Setting up webhook
       var cert = new Telegram.Bot.Types.FileToSend("certificate.pem", new FileStream(Server.MapPath("~/Resources/certificate.pem"), FileMode.Open));
      Telegram.Bot.Api bot = new Telegram.Bot.Api("mytoken");
      bot.SetWebhook("https://myhost:8443/api/webhook").Wait();
}
```

I've looked up, and it seems Telegram has no problem with .pem certificates.

**Comment by MrRoundRobin** [comment]
```c#
bot.SetWebhook("https://myhost:8443/api/webhook").Wait();
```
must be 
```c#
bot.SetWebhook("https://myhost:8443/api/webhook",cert).Wait();
```

**Comment by blacksagres** [comment]
Sorry, I've pasted the wrong snipped, I've added the file and still no response. I also bought a certificate from GoDaddy for 4 bucks to see if that was the problem, but even with that it doesn't seem to work.

**Comment by MrRoundRobin** [comment]
Can you show me the actual handler?

**Comment by blacksagres** [comment]
Of course. The setup that I have is just an mvc application with an index page and an API controller.
This is my app_start:

```javascript
void Application_Start(object sender, EventArgs e) {
      // Code that runs on application startup
      AreaRegistration.RegisterAllAreas();
      GlobalConfiguration.Configure(WebApiConfig.Register);
      RouteConfig.RegisterRoutes(RouteTable.Routes);
      // Setting up webhook
       var cert = new Telegram.Bot.Types.FileToSend("certificate.pem", new FileStream(Server.MapPath("~/Resources/certificate.pem"), FileMode.Open));
      Telegram.Bot.Api bot = new Telegram.Bot.Api("mytoken");
      bot.SetWebhook("https://myhost:8443/api/webhook", cert).Wait();
}
``` 

My controller with the post method which should receive the updates from telegram:

```javascript
public class WebhookController: ApiController
    {
        #region Properties

        private Telegram.Bot.Api Bot { get; set; }

        #endregion

        #region Constructor

        /// <summary>
        /// Basic constructor for the api controller
        /// </summary>
        public WebhookController() : base()
        {
            Bot = new Telegram.Bot.Api(ConfigurationManager.AppSettings["TelegramTokenClone"]);
        }

       #endregion

       public async Task<IHttpActionResult> Post(Update update) {
       var message = update.Message;

      Console.WriteLine("Received Message from {0}", message.Chat.Id);

       if (message.Type.Equals(MessageType.TextMessage)) {
        // Echo each Message
        await Bot.SendTextMessage(message.Chat.Id, message.Text);
       }
      else if (message.Type.Equals(MessageType.PhotoMessage)) {
        // Download Photo
        var file = await Bot.GetFile(message.Photo.LastOrDefault()?.FileId);

        var filename = file.FileId + "." + file.FilePath.Split('.').Last();

        using (var saveImageStream = System.IO.File.Open(filename, FileMode.Create)) {
          await file.FileStream.CopyToAsync(saveImageStream);
        }

        await Bot.SendTextMessage(message.Chat.Id, "Thx for the Pics");
      }

      return Ok();
    }
 }
```

**Comment by NeelBhatt** [comment]
Might be too late to comment here but it is finally supported by .Net! Have a look here: https://neelbhatt40.wordpress.com/2015/10/14/webhooks-in-asp-net-a-visual-studio-extension/

**Comment by blacksagres** [comment]
That's very good news. Have you tried it yet? I am excited to give it a go ASAP.

**Comment by NeelBhatt** [comment]
Yes I have tried it. I will soon put some code in Github for demo project. @blacksagres

**Comment by blacklabelmee** [comment]
@blacksagres  did you managed to setup the webhook finally?

**Comment by blacksagres** [comment]
@blacklabelmee Unfortunately no.

**Comment by blacklabelmee** [comment]
@blacksagres thanks for your reply . i'm still trying if i succeeded will notify you :)

**Comment by Hamidnwo** [comment]
There's a trick with the Certificatse: You should create a plain text certificate chain if you're using a subdomain. The chain must be from the subdomain all the way to the root. I included three .pem files and added them to a single file using Type command in cmd (type sub.domain.com.pem intermediate.pem root.pem >> bundle.pem). Make sure you delete any bundle.pem file before generating a new one. 

Take a look at this:
https://core.telegram.org/bots/webhooks#setting-a-verified-webhook-with-an-untrusted-root
