### ISSUE TITLE
How to NOT update offset when using Bot.StartReceiving()  ?

### ISSUE THREAD

**Issue by Newgel** [MrRoundRobin/telegram.bot#394]
Is there any way of instructing StartReceiving() to NOT add an offset to getUpdates url? The reason for that is I have a few copies of the same bot running on different machines at the same time. I want all of them to receive all messages. Each bot will internally keep track of previously messages to avoid repeating actions. 
Before someone asks... it is a monitoring bot. I want to manually send a "/ping" command and all online machines will answer with a "Machine <ip> is alive" message.

So, how do I disable StartReceiving() from updating offset? 
Thanks,
Newgel

**Comment by MrRoundRobin** [comment]
you can implement your own `StartReceiving` method and leave out the offset parameter when calling `GetUpdates`
