### ISSUE TITLE
delete all the messages get by getUpdates

### ISSUE THREAD

**Issue by YasserDivaR** [MrRoundRobin/telegram.bot#396]
how to delete all the messages get by getUpdates
https://api.telegram.org/bot273621415:AAEk6geENUV_HDDmIUOXBlbzdnRBgOy0pB8/getUpdates

NuGet Package Version:* (e.g. 10.3.0)

*.NET Version:* (4.5)

*IDE:* (vs 2017)

*App:* (Desktop)

**Comment by MrRoundRobin** [comment]
@YasserDivaR Call get Updates With Offset  higher than the Last Update id

**Comment by YasserDivaR** [comment]
Hi, I have a problem with this library that if no other Setwebhook receive a message, then it's a solution
