### ISSUE TITLE
GetUpdates() ignores some parameters

### ISSUE THREAD

**Issue by wallnutkraken** [MrRoundRobin/telegram.bot#42]
offset is completely ignored
if limit goes above 100, it's ignored

is this intended?

**Comment by MrRoundRobin** [comment]
https://core.telegram.org/bots/api#getupdates

"Limits the number of updates to be retrieved. Values between 1—100 are accepted. Defaults to 100"

**Comment by wallnutkraken** [comment]
Thanks, sorry!

**Comment by MrRoundRobin** [comment]
no problem :)
