### ISSUE TITLE
In calling 'SendVideo' method, an error occurs 

### ISSUE THREAD

**Issue by Hamix** [MrRoundRobin/telegram.bot#44]
hi
Error:
**A task was canceled.**

Code:
```c#
var stream = new FileStream(fi.FullName, FileMode.Open);
var fileToSend = new FileToSend(fi.Name, stream);
await rBot.SendVideo(update.Message.Chat.Id, fileToSend,0, "", 0, Menus.UserMenu.UserMenuKeyboard);
```
File info:
.mp4, 4m

*I think request times out and throws a WebException.*
ty.

**Comment by MrRoundRobin** [comment]
Sorry for the delayed answer, you are correct, the default timeout for the HTTPClient is 100 seconds.

I'll increase this for file uploads.
