### ISSUE TITLE
Problem in Version 4!

### ISSUE THREAD

**Issue by Dariush-Tasdighi** [MrRoundRobin/telegram.bot#49]
I updated your nice lib to my applicaion... (Version 4)

But unfortunately sending Phone, Audio,... does not response!

It means that the file will be uploaded but after sendAudio, SendPhoto... system freazes!

Regards
Dariush Tasdighi

**Comment by MrRoundRobin** [comment]
OK, I'll check that tomorrow

**Comment by MrRoundRobin** [comment]
Can't reproduce this, i sent a 30m video and a 6,7m mp3 file successfully.

maybe this was due to #44 but then you should have seen an exception.

can you test with [v4.1](https://www.nuget.org/packages/Telegram.Bot/4.1.0.34511)
