### ISSUE TITLE
Error In Sending Icon's as a Document !

### ISSUE THREAD

**Issue by LuckyPed** [MrRoundRobin/telegram.bot#5]
HI,
First I want to Thanks you for your great library :+1: 

now on to the issue , 
it seems that Telegram's document , when sending an icon , in the thumb field,  is empty !
thus giving error , as u made it in your code that if there is a thumb , then width + height + field_id  are all Required !
they are always there if u send other kind of documents so it's fine , but for icon , this error happened ,
I temporary fixed it by setting these three to default which is not required , but i don't know if u want to make a better change for it :D 

Here a Json for Icon : 

```
{"ok":true,"result":[{"update_id":918502747,
"message":{"message_id":188,"from":
{"id":120865239,"first_name":"Pedram","last_name":"Saeedi"},"chat":
{"id":120865239,"first_name":"Pedram","last_name":"Saeedi"},"date":1436357039,"document":
{"file_name":"favicon.ico","mime_type":"image\/vnd.microsoft.icon","thumb":
{},"file_id":"BQADBAADCAAD10E0BwVrR0oxKKibAg","file_size":2462}}}
```

**Comment by MrRoundRobin** [comment]
Okay, this looks like a bug at telegram or the dosumentation. I'll see what i can do to workaroud this tomorrow,

thanks for reporting

**Comment by LuckyPed** [comment]
your welcome :D
