### ISSUE TITLE
Exception in SendTextMessage

### ISSUE THREAD

**Issue by anubhavranjan** [MrRoundRobin/telegram.bot#54]
I am getting an exception when trying to SendTextMessage.
I am trying to reply to the Chat Message received in the WebHook.
My System is Asp.Net MVC and I am using the SDK from NuGet: Version 5.0.0.37161

var result = await tgClient.SendTextMessage(update.Message.Chat.Id, "Test Message");
```
No MediaTypeFormatter is available to read an object of type 'ApiResponse`1' from content with media type 'text/html'.

at System.Net.Http.HttpContentExtensions.ReadAsAsyncT
at System.Net.Http.HttpContentExtensions.ReadAsAsyncT
at System.Net.Http.HttpContentExtensions.ReadAsAsyncT
at Telegram.Bot.Api.d__451.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter1.GetResult()
at TvShowsReminder.d__1.MoveNext()
```

**Comment by amastaneh** [comment]
- Error comes after upgrade Newtonsoft.Json to v8.0.2
- Just in "SendTextMessage" with string 'chat.Id'

Exception:
Message: No MediaTypeFormatter is available to read an object of type 'ApiResponse`1' from content with media type 'text/html'.
Source: System.Net.Http.Formatting
Help Link:
Stack Trace:    at System.Net.Http.HttpContentExtensions.ReadAsAsync[T](HttpContent content, Type type, IEnumerable`1 formatters, IFormatterLogger formatterLogger, CancellationToken cancellationToken)
   at System.Net.Http.HttpContentExtensions.ReadAsAsync[T](HttpContent content, Type type, IEnumerable`1 formatters, IFormatterLogger formatterLogger)
   at System.Net.Http.HttpContentExtensions.ReadAsAsync[T](HttpContent content, IEnumerable`1 formatters)
   at Telegram.Bot.Api.<SendWebRequest>d__78`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TelegramTaadol.Bot.<SendNewsAsync>d__7.MoveNext()

**Comment by amastaneh** [comment]
I think we need to change `ReadAsAsync` to `ReadAsStringAsync` at https://github.com/MrRoundRobin/telegram.bot/blob/master/src/Telegram.Bot/Api.cs#L862

**Comment by MrRoundRobin** [comment]
Hi,

what platform are you using?

"No MediaTypeFormatter [...]  from content with media type 'text/html'" indecates that the response from the API is malformed, it should be application/json....

can you sniff what's send and received, for example with wireshark or fiddler?

**Comment by amastaneh** [comment]
Thank you for your response.

Q1: Both application stopped after upgrade nugets
- Desktop (Windows Application, WPF, .Net 4.5)
- Web (MVC 4.0, ASP .Net 4.5)

Q2: i'm working on it

**Comment by amastaneh** [comment]
After test https://api.telegram.org/bottoken/sendMessage with **Postman**
After one success, i received this message after some seconds.

```
<html>
    <head>
        <title>504 Gateway Time-out</title>
    </head>
    <body bgcolor="white">
        <center>
            <h1>504 Gateway Time-out</h1>
        </center>
        <hr>
        <center>nginx/1.6.2</center>

    </body>

</html>
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
```

**Comment by MrRoundRobin** [comment]
So please try contacting [@BotSupport](https://telegram.me/botsupport)

my test bots working

**Comment by amastaneh** [comment]
Finally the problem has gone.
Thank you @MrRoundRobin and [@BotSupport](https://telegram.me/BotSupport)

![image](https://cloud.githubusercontent.com/assets/6195199/12492370/1f22c05c-c095-11e5-9d25-240beb50f81c.png)
