### ISSUE TITLE
File Sent Status!

### ISSUE THREAD

**Issue by MRACHINI** [MrRoundRobin/telegram.bot#55]
hey,

new to C#, building a file downloader/uploader for telegram, could you give more clear examples on how to check the status of a message if it was successfully sent or not, lets say connection was dropped...

**Comment by MrRoundRobin** [comment]
Hi,
If the functions return the corresponding Message object, the Telegram servers successful received the message. If there was a problem with the underlining HTTP request, the exception will be thrown to your code.

**Comment by MRACHINI** [comment]
i was actually waiting for "message" return so i check the status if true or false as per telegram api documentation, but i think I'm doing something wrong.
small example:

var Bot = new Telegram.Bot.Api("testtesttesttesttesttesttesttesttesttesttest");
await Bot.SendChatAction(16582265, ChatAction.UploadDocument);
Stream fs = System.IO.File.OpenRead(@"C:\testfile.txt");
var document = new FileToSend("testfile.txt", fs);
Telegram.Bot.Types.Message x = await Bot.SendDocument(1344, document);


now how do i check x for the return message !?

**Comment by MrRoundRobin** [comment]
You can check if ```x``` is null, but if there is is any error, there should be an exception.
see [Api.cs](https://github.com/MrRoundRobin/telegram.bot/blob/master/Telegram.Bot/Api.cs#L742-L743)

**Comment by MRACHINI** [comment]
OK so you are handling both situations:
1. when telegram returns msg but "ok" is false.
and
2. when there is no response from telegram at all, or some error.

thank you for the help :)

**Comment by narimanmaster** [comment]
sorry sir
i have a question..!
how i can send a document with telegram bot sharp?!
