### ISSUE TITLE
Mark message as read

### ISSUE THREAD

**Issue by rogercorrea** [MrRoundRobin/telegram.bot#56]
Please,
How can I mark a message as received and read by the robot?
My reading is the same messages even when it gets a new one.

Thanks!

**Comment by rogercorrea** [comment]
I used the "offset" parameter of the function "Get Updates" and it worked. But found nothing in documentation and I was lost.

I found solution reading the "Main" function in the one project what is used TeleBotDotNet. The developer used lastUpdateId variable to save last message Id read and call "GetUpdates" using the value in the "offset" parameter.
https://github.com/Naxiz/TeleBotTicTacToe/blob/master/Program.cs

Thanks!

**Comment by MrRoundRobin** [comment]
Hi,

as this is mainly a wrapper library you can always look at the [official documentation](https://core.telegram.org/bots/api).
Your question is answered [here](https://core.telegram.org/bots/api#getupdates) and in the xml documentation tags
