### ISSUE TITLE
Group messages

### ISSUE THREAD

**Issue by bezobraz1e** [MrRoundRobin/telegram.bot#60]
When i do command without "/" bot executes the command in private message, but in group chat bot executes the command only with "/" in the beginning of the message. Adding the "/" at the beginning of the message by "/" + update.message.text does not help. What to do?

**Comment by MrRoundRobin** [comment]
That's because by default a bot is in privacy mode. See [here](https://core.telegram.org/bots/faq#what-messages-will-my-bot-get)
