### ISSUE TITLE
Telegram.Bot project doesn’t Build because '=>' notation

### ISSUE THREAD

**Issue by leandromgarcia** [MrRoundRobin/telegram.bot#64]
Hello, I download the code and execute the ‘Install-Package Telegram.Bot’ command. But my Telegram.Bot project doesn’t Build, showing many errors on the code like this: public Task<User> GetMe() => SendWebRequest<User>("getMe");…. Almost all errors occurs in the Api.cs file, because of the notation ‘=>’.

To be honest I never seen this kind of code in this context…. Are there something else I should do?

* I am using the Visual Studio 2012

Thank you,

**Comment by MrRoundRobin** [comment]
the "=>" notation, known as ["Expression-bodied function members"](https://github.com/dotnet/roslyn/wiki/New-Language-Features-in-C%23-6#expression-bodies-on-method-like-members) is an C# 6 Feature.

So you need to use Visual Studio 2015 to build the library

**Comment by Artikud** [comment]
You can using Visual Studio 2013 too, but you need download update  see http://stackoverflow.com/questions/27093908/how-to-enable-c-sharp-6-0-feature-in-visual-studio-2013
