### ISSUE TITLE
PCL support removed

### ISSUE THREAD

**Issue by paulspiteri** [MrRoundRobin/telegram.bot#69]
Hi
I see that version 4 changed from a PCL to NET45 lib type. Can you give some guidance on why this happened and how likely that I'll be able to change it back on my fork?
Cheers
Paul

**Comment by MrRoundRobin** [comment]
If I remember correctly there where dependencies or functions which aren't available in PCLs.

But i'm working on changing the project to the new format with project.json an multiple supported frameworks (such as Normal .NET and CoreCRL)
