### ISSUE TITLE
SendRequest method is not responding in mvc and win app

### ISSUE THREAD

**Issue by NaderStar** [MrRoundRobin/telegram.bot#7]

**Comment by NaderStar** [comment]
Api.cs
line 534
response = await client.GetAsync(uri);

**Comment by NaderStar** [comment]
i think it should replace with 

response = await client.GetAsync(uri).ConfigureAwait(false);

for deadlock thread reasons

**Comment by NaderStar** [comment]
http://stackoverflow.com/questions/9895048/async-call-with-await-in-httpclient-never-returns

**Comment by NaderStar** [comment]
thanx robin

**Comment by NaderStar** [comment]
private async Task<T> SendWebRequest<T>(string method, Dictionary<string, object> parameters = null)
		{
			var response = await SendRequest(method, parameters).ConfigureAwait(false);

			ApiResponse<T> responseObject = null;
			await response.Content.ReadAsStreamAsync().ContinueWith((taskwithresponse) =>
				{
					var jsonString = response.Content.ReadAsStringAsync();
					jsonString.Wait();
					responseObject = JsonConvert.DeserializeObject<ApiResponse<T>>(jsonString.Result);

				}).ConfigureAwait(false);

			if (responseObject.Ok)
			{
				return responseObject.ResultObject;
			}

			throw new Exception(responseObject.Message);
		}

**Comment by NaderStar** [comment]
check it out
just worked

**Comment by MrRoundRobin** [comment]
Ok, I read some articles about this. finally I understood the problem :smile:

**Comment by NaderStar** [comment]
good job thanx :-)
