### ISSUE TITLE
Can not send TextMessage

### ISSUE THREAD

**Issue by dinhducit** [MrRoundRobin/telegram.bot#71]
when i try to send a message, i just got result: msg	Id = 14, Status = WaitingForActivation, Method = "{null}", Result = "{Not yet computed}"
what does it mean?
how can i send message to phone number as well?
thank for your help!

**Comment by MrRoundRobin** [comment]
The "{Not yet computed}" has to do with Async/Await, pleas read [MSDN](https://msdn.microsoft.com/en-us/library/hh191443.aspx)

And you can't send messages to phone numbers, please read the [Introduction to Bots](https://core.telegram.org/bots)
