### ISSUE TITLE
hellobot.php not receiving webhook calls

### ISSUE THREAD

**Issue by alejandro-anv** [MrRoundRobin/telegram.bot#73]
I am just testing Telegram bots. I downloaded hellobot php program from samples, placed on the root of the web server, and created a bot. Repllaced the BOT_TOKEN in the source and changed the WEBHIOOK_URL. 

Executed the .php in command-line in order to register the webhook and the response was "Request was successfull: Webhook was set" but I don't receive any get or post for the URL I set.

I think there may be a problem with the ssl certificate. It is a valid let's encrypt cert but I think may be it is not accepted. 

I also added the certificate field by insering the let's encrypt cert but I am not user this is the right way to do this:

apiRequest('setWebhook', array(
    'url' => isset($argv[1]) && $argv[1] == 'delete' ? '' : WEBHOOK_URL
   ,'certificate'=>file_get_contents('https://letsencrypt.org/certs/lets-encrypt-x1-cross-signed.pem')
   ) );

**Comment by MrRoundRobin** [comment]
@alejandro-anv If it is an offical trusted certificat, you dont need to specify it in setwebhook, please See the Telegramm api docs

**Comment by alejandro-anv** [comment]
Ok, I removed the cert field. But steels not working. 

The webserver log does not register any access to the script. What can I test?

**Comment by MrRoundRobin** [comment]
If you don't get any requests, that's maybe a problem with your set up or something.

and this is not the bug tracker for the php library ;) see [here](https://github.com/irazasyed/telegram-bot-sdk)

**Comment by alejandro-anv** [comment]
Hummm... but if I calls the URL from my browser, it works and the request is logged...

**Comment by MrRoundRobin** [comment]
so then telegram doesn't call it. try contacting [@botsupport](https://telegram.me/botsupport)
