### ISSUE TITLE
Got Exception when using getUpdates function

### ISSUE THREAD

**Issue by dinhducit** [MrRoundRobin/telegram.bot#74]
I got exception look like attach file, pls let me know a reason.

![image](https://cloud.githubusercontent.com/assets/13290578/12238534/0137deaa-b8b7-11e5-9cc3-24ca603d25d6.png)

code for test:
```c#
            var offset = 0;
            while (true)
            {
                var updates = await bot.GetUpdates(offset);

                foreach (var update in updates)
                {
                    if (update.Message.Type == MessageType.TextMessage)
                    {
                        await bot.SendChatAction(update.Message.Chat.Id, ChatAction.Typing);
                        await Task.Delay(2000);
                        var t = await bot.SendTextMessage(update.Message.Chat.Id, update.Message.Text);
                        Console.WriteLine("Echo Message: {0}", update.Message.Text);
                    }

                    if (update.Message.Type == MessageType.PhotoMessage)
                    {
                        var file = await bot.GetFile(update.Message.Photo.LastOrDefault()?.FileId);

                        Console.WriteLine("Received Photo: {0}", file.FilePath);

                        var filename = file.FileId + "." + file.FilePath.Split('.').Last();

                        using (var profileImageStream = File.Open(filename, FileMode.Create))
                        {
                            await file.FileStream.CopyToAsync(profileImageStream);
                        }
                    }

                    offset = update.Id + 1;
                }

                await Task.Delay(1000);
            }
```

**Comment by MrRoundRobin** [comment]
Hi,

the error comes from [Message.cs#L208](https://github.com/MrRoundRobin/telegram.bot/blob/master/Telegram.Bot/Types/Message.cs#L208). I think there needs to be an "UnknownMessage" type rather than an exception. 

And maybe it needs a "ServiceMessage" for events like group joins and so on...

i'll look into it tomorrow.

**Comment by dinhducit** [comment]
Yes, I think so, I have look into json string result and see it is a new_chat_participant type, not text or photo type, so we got exception.
And new_chat_participant type is updates message from group, so I have question how we can get update message from group?

**Comment by MrRoundRobin** [comment]
Okay, so try v6.0.2. 
I uploaded it a few Minutes ago

**Comment by dinhducit** [comment]
can you share source code, I need it :)

**Comment by MrRoundRobin** [comment]
What do you mean? Source is already pushed

**Comment by dinhducit** [comment]
my mean is, you can merge code you updated to fix this bug to current source code on github :)

**Comment by MrRoundRobin** [comment]
b3901f8567241408febf23200ff36cdc0f8f1e4d ?

**Comment by dinhducit** [comment]
ok, thank a lot, bro :)
