### ISSUE TITLE
HTML style support

### ISSUE THREAD

**Issue by amastaneh** [MrRoundRobin/telegram.bot#76]
`HTML` style is so like to `Markdown` style for `parse_mode`
I think we need an enumeration instead if boolean in 
https://github.com/MrRoundRobin/telegram.bot/blob/master/src/Telegram.Bot/Types/InlineQueryResult.cs#L49
like
```C#
public enum ParseMode{ None, Markdown, HTML }
```

**Comment by MrRoundRobin** [comment]
wait 5 minutes ;)

**Comment by MrRoundRobin** [comment]
5f93d42443109d3c9d0eef0e8e8e74b4e5e13b91
