### ISSUE TITLE
The life cycle of "Chat Id"

### ISSUE THREAD

**Issue by bgani** [MrRoundRobin/telegram.bot#80]
I know telegram stores messages that sent to bot about 24 hour, then delete them. Will "Chat Id" be deleted or changed to a new one if user will remove the bot from contacts and don't add bot again for 24 hours ? Or "Chat Id" wil be saved until i delete my bot ?  I am gonna save "Chat Id" and "message text"  for statistics. Thats why "Chat Id" must be unique for me.

**Comment by MrRoundRobin** [comment]
@bgani This is something that is controled by Telegramm, you can ask @BotSupport
