### ISSUE TITLE
Create an IApi interface

### ISSUE THREAD

**Issue by micdenny** [MrRoundRobin/telegram.bot#82]
What about creating an IApi interface that wraps the actual Api implementation, so it is possible to inject it and be able to be opened for unit testing.

**Comment by MrRoundRobin** [comment]
so this would simply be this interface: https://gist.github.com/MrRoundRobin/dd2d392b1167738ca078 ?

**Comment by micdenny** [comment]
yes that is :smile:

**Comment by MrRoundRobin** [comment]
should be solved with PR #216

**Comment by micdenny** [comment]
Great, thank you!
