### ISSUE TITLE
System.AggregateException on Bot.GetMe

### ISSUE THREAD

**Issue by williamokano** [MrRoundRobin/telegram.bot#83]
Hi guys, I'm getting this exception whenever I try to run the demos.

The inner exception says that the Task have been cancelled.

Any ideas?

**Comment by Ruberoid** [comment]
AggregateException - is compilation of set or possibly just one exception. Take a look at inner details.

**Comment by williamokano** [comment]
I took, as I said, the inner exception just say, task cancelled.

By the way, the problema stopped happening, I don't know why, just stopped.

I'll close this issue, and if this start happening again, I'll update you.

Thanks

**Comment by williamokano** [comment]
@Ruberoid I found the problem.

The HttpClient is getting timeout when the getUpdates have nothing new for me.

Any suggestions? Just add a try catch and keep the life going?

**Comment by Sobiru** [comment]
I also have this exact issue. I'm using 8.0.0 version. I should mention when i run the [Echo Demo from official examples](https://github.com/MrRoundRobin/telegram.bot.examples/tree/master/Telegram.Bot.Examples.Echo)  It works just fine and I never get an exception. So maybe this is something only in the latest version.

**Comment by williamokano** [comment]
Yeah, I forgot to mention that when I run the echo demo this behavior doesn't happen.

**Comment by Sobiru** [comment]
@williamokano , In your earlier post you said:

> The HttpClient is getting timeout when the getUpdates have nothing new for me. Any suggestions? Just add a try catch and keep the life going?

But for me, I get an exception even on the `await Bot.GetMe()`, Are you sure this only happens when we don't have new updates?

**Comment by williamokano** [comment]
Not sure. Sometimes this also happening to me on the getMe too.

Em qui, 11 de fev de 2016 21:17, Sobiru <notifications@github.com> escreveu:

**Comment by Sobiru** [comment]
I just went ahead and uninstalled v8.0.0 from my project and then installed the v7.0.0 version with this command:
 `Install-Package Telegram.Bot -Version 7.0.0`
 Now I get no exceptions whatsoever so I'm starting to think it is a version issue.

**Comment by MrRoundRobin** [comment]
should be fixed in f8ebeaf
