### ISSUE TITLE
Send gif with caption

### ISSUE THREAD

**Issue by abadakhshan** [MrRoundRobin/telegram.bot#84]
how can send gif with caption?
gif sends with sendDocument  but sendDocument dosent have caption parameter
but i sess gifs with caption in telegram

**Comment by abadakhshan** [comment]
hi
i found answer!!!
gif sends with sendDocument but sendDocument dosent have caption parameter . its true
but you can send caption with sendDocument !!!
and telegram show this caption with gif file
pls add caption parameter to SendDocument method  or add anoyher fuction "SendGif"

tanx

**Comment by williamokano** [comment]
According to the API, on the message you can set the Message object and set the Caption, which is an optional parameter.

https://core.telegram.org/bots/api#sendphoto

As you can see https://github.com/MrRoundRobin/telegram.bot/blob/master/src/Telegram.Bot/Types/Message.cs#L103, you can set the Caption along with the PhotoSize

Should work

**Comment by MrRoundRobin** [comment]
added in aa845a3399e962d989ba8b8c30c8d0fed4047e59
