### ISSUE TITLE
Setting webhook with an empty string causes error

### ISSUE THREAD

**Issue by Hamcker** [MrRoundRobin/telegram.bot#89]
when set the webhook with empty string "", it causes this error:

    No MediaTypeFormatter is available to read an object of type 'ApiResponse`1' from content with media type 'text/html'.

**Comment by Bouki6** [comment]
its not just web hook. if you try to call any methods without an valid Bot Token you catch the same  exception.

**Comment by MrRoundRobin** [comment]
should be solved
