### ISSUE TITLE
[Feature Request] A multilevel keyboard in a single command

### ISSUE THREAD

**Issue by futuretechsoft** [MrRoundRobin/telegram.bot#9]
Hi,  We really appreciated your bot API, and we want to use this API to create own bot for business.
Basically our requirement is that we want select product by asking multiple question with selective option 

Example: our user want buy smartphone we want to implement in following steps
Step 1)  Brand :  Apple,  Samsung,  BlackBerry  <b>[Next]</b>
Step 2)  <b>[Back]</b> Memory : 8gb,  16gb,  32gb,  64gb  <b>[Next]</b>
Step 3) <b>[Back]</b> Camera :  8mp , 16mp <b>[Next]</b>
Step 4) <b>[Back]</b> Budget : 10000-14999, 15000-24900 , above 25000 <b>[Finish]</b>

As we mentioned our scenario as above, first we will show Brand, then Memory, then Camera and finally Budget, in which user can select multiple values too.
We want to provide all this feature in a single keyboard selection event, which can be operated by a user in ease way.
In current scenario, a user waits until next filter category is shown, and all this category is shown one by one until the user clicks the finish. Unfortunately this conversation will be too long, and tricky if user wants to change any filtration category (with <b>[Next]</b> or <b>[Back]</b> button as we mentioned in example). We can only send list of products after finish event occurs. But instead of that, we want to have a keyboard in which a user can select values and that selection appears in typing area, which can be changed and submitted at only final state in one single message.

**Comment by MrRoundRobin** [comment]
If i understand you correct this is nothing I could provide. That sounds like 'Client' behaviours.

**Comment by futuretechsoft** [comment]
Hi,
       Currently we are facing issue, that we can't control reply keyboard markup, our requirement is, we  basically want to select multiple value from keyboard and send it to bot in one message. so will it be possible..?
