### ISSUE TITLE
why there is filename in FileToSend?

### ISSUE THREAD

**Issue by Bouki6** [MrRoundRobin/telegram.bot#90]
Hello. i tried to to send a photo with `SendPhoto` method but `FileToSend` structure has a string property named:`filename `. the Telegram API doesn't require file name in order to send a photo, video, voice ,...
i wonder why you need it?
thanks.

**Comment by MrRoundRobin** [comment]
The [doku](https://core.telegram.org/bots/api#inputfile) says:

> **InputFile**
> This object represents the contents of a file to be uploaded. Must be posted using multipart/form-data in the usual way that files are uploaded via the browser.

i think it was needed that the telegram server could determinate the file type, but not sure

**Comment by Bouki6** [comment]
i guess telegram server determine the file type base on the file header. any way its not a big deal.
thanks.
