### ISSUE TITLE
Sending a photo?

### ISSUE THREAD

**Issue by Milaine** [MrRoundRobin/telegram.bot#94]
Hello, I am currently trying to create a bot with this library, and so far it worked great by just fiddling around a bit.
I can send photos with their photo ID once I've sent them to telegram before:
await Bot.SendPhoto(message.Chat.Id, "[photo ID]");
what I want to know is how to do this with a file off a webpage, in this case:
"http://thecatapi.com/api/images/get?format=src&size=med&type=jpg"
I think I have to download it as a bytestream/bytearray but I really have no idea.
Googling stackoverflow didnt help either :P 
I'd really appreciate some help ^^"

**Comment by Milaine** [comment]
`var request = WebRequest.Create("https://upload.wikimedia.org/wikipedia/commons/8/8f/Hippie-flower_-_Virginia_-_ForestWander.jpg");

using (var response = request.GetResponse())
{
    var responseStream = response.GetResponseStream();
    var fileToSend = new FileToSend("ForestWander.jpg", responseStream);
    await bot.SendPhoto(123456789, fileToSend);
}`

Nevermind I'm an idiot that doesnt read old issues before making a new one.
everything works fine, what is this "ForestWander.jpg" tho?

**Comment by Milaine** [comment]
And I've got this error:
"An unhandled exception of type 'System.AggregateException' occurred in mscorlib.dll"
after the pic was sent

**Comment by guitarxhero** [comment]
Hello!

Have you tried without the `await` keyword?

**Comment by Milaine** [comment]
what does the `await` keyword even do? I'll try it now tho

**Comment by Milaine** [comment]
it turned out that this error happens even if I don't use the send photo.
I'll open a new issue I guess.
