### ISSUE TITLE
gif is converted to jpg

### ISSUE THREAD

**Issue by cnokobe** [MrRoundRobin/telegram.bot#95]
Hi there, I'm trying to send .gif file with the code below, but when the bot sends the photo - it is in .jpeg format. What am I doing wrong?

`using (Bitmap bitmap = new Bitmap(value, false))
using (Stream stream = bitmap.ToStream(ImageFormat.Gif))
{
    FileToSend fs = new FileToSend(value, stream);
    var ttt = Bot.SendPhoto(update.Message.Chat.Id, fs);
    ttt.Wait();
    stream.Close();
    fs.Content.Close();
}

public static Stream ToStream(this Image image, ImageFormat format)
{
    MemoryStream stream = new System.IO.MemoryStream();
    image.Save(stream, format);
    stream.Position = 0;
    return stream;
}
`

**Comment by MrRoundRobin** [comment]
just tested sending gifs with sendDocument, which worked perfectly

```c#
using (var fileStream = new FileStream(@"P:ath\to\picture.gif", FileMode.Open))
{
    var fileToSend = new FileToSend("picture.gif", fileStream);
    await Bot.SendDocument(message.Chat.Id, fileToSend, "optimal Caption");
}
```

**Comment by cnokobe** [comment]
With Bot.SendDocument the .gif is sent as any other file, so you have to press "download" button first, .gif is not starting automatically.

**Comment by cnokobe** [comment]
@MrRoundRobin can you help me please, I want to send .gif and play it directly without need to press "Download" button. Is there any solution for this?
