### ISSUE TITLE
"An unhandled exception of type 'System.AggregateException' occurred in mscorlib.dll"

### ISSUE THREAD

**Issue by Milaine** [MrRoundRobin/telegram.bot#96]
Hello, I get this error while running my bot.
(I was just writing an long text about one code passage I deemed responsible for this just to then get the same crash and delete my whole post)

`

       private static async Task RunBot()
        {

            var Bot = new Telegram.Bot.Api("Mytoken");

            var me = await Bot.GetMe();

            Console.WriteLine("Hello my name is {0}", me.Username);

            var offset = 0;

            while (true)
            {
                var updates = await Bot.GetUpdates(offset);

                foreach (var update in updates)
                {
                    switch (update.Type)
                    {
                        case UpdateType.MessageUpdate:
                            var message = update.Message;

                            switch (message.Type)
                            {
                                case MessageType.TextMessage:

                                    if (message.Text.Contains("Something"))
                                    {
                                        await Bot.SendTextMessage(message.Chat.Id, "Reply");
                                        break;
                                    }
                                    break;
                            }
                            break;
                    }

                    offset = update.Id + 1;
                }
            }
        }

`
I ran my bot in this configuration and it still crashed. that means something is elementarily wrong with it. Can somebody give it a look and tell me what I did wrong please?

**Comment by guitarxhero** [comment]
Hello!

Just to be use, is `"MyToken"` used for placeholder for this issue?

When I ran the debugger, it seemed to have stopped at `var me = await Bot.GetMe();`.

This returns a `Task<User>`. Which doesn't have a `Username` property.

However when I try with `User me = Bot.GetMe().Result;`, it works again for me.

Notes:
- Try giving a pause between the update fetching with `System.Threading.Thread.Sleep(int)`.
- I personally use events with this library, it's nice! Nothing is async in my bot.
- The following code gives me no error and no warnings:
```csharp
static void Main(string[] args)
{
    RunBot();
}

static async void RunBot()
{
    var Bot = new Telegram.Bot.Api(KEY);
    
    // [...]
```

**Comment by Milaine** [comment]
My Token is a placeholder for my token.

I'm not sure if you understood correctly but my bot does work, it just crashes after ~3 minutes.

I'm not sure about what you mentioned then, but if I interpret it correctly, no, it does give me the name of the bot.

The first 3 lines are taken from the libraries example classes.

When and how do you use events? Can you give me an example?

As I said, it does run without any errors, it just crashes after a while.

**Comment by guitarxhero** [comment]
Here's an example with events, hope you'll like me for this ~

```csharp
static Api Service;

static void Main(string[] args)
{
    Service = new Api(TOKEN);
    Service.MessageReceived += Client_MessageReceived;
    Service.StartReceiving();
}

static void Client_MessageReceived(object sender, MessageEventArgs e)
{
    Service.SendTextMessage(e.Message.Chat.Id, "Hello to you back!");
}
```

Been 2 days it hasn't crashed. When it does, it's the library.

**Comment by Milaine** [comment]
So you basically replace

`

        while (true)
        {
            var updates = await Bot.GetUpdates(offset);

            foreach (var update in updates)
            {
                switch (update.Type)
                {
                    case UpdateType.MessageUpdate:
                        var message = update.Message;

                        switch (message.Type)
                        {
                            case MessageType.TextMessage:

                                if (message.Text.Contains("Something"))
                                {
                                    await Bot.SendTextMessage(message.Chat.Id, "Reply");
                                    break;
                                }
                                break;
                        }
                        break;
                }

                offset = update.Id + 1;
            }
        }
`

with just an event and this `Service.StartReceiving();`?
What does the ``+=`` mean tho?
and can't I just use `static void Service.MessageReceived(object sender, MessageEventArgs e)`?
I really like that concept, if you could introduce me to it a bit that'd really be awesome :3

**Comment by guitarxhero** [comment]
Will do!

Now now, events.

`+=` Means that it's subscribing to an event (`MessageReceived`), in this case: `Client_MessageReceived`. So `Service.MessageReceived += Client_MessageReceived;` means that you subscribe `Client_MessageReceived` (a delegate) to the `MessageReceived` event.

You can also unsubscribe to an event with `-=`.

So when you get a message, the `MessageReceived` event fires and leads to `Client_MessageReceived`.

`e` is the argument with all the info you need (like e.Message contains the message with the user, id, etc.)

And `Service.SendTextMessage(e.Message.Chat.Id, "Hello to you back!");` basically sends a message to the person who messaged the bot.

Don't worry, the library comes with other events like:
- `ChosenInlineResultReceived`
- `InlineQueryReceived`
- `UpdateReceived`

Note: Add a `Console.ReadLine();` at the end of the `Main` method so the app doesn't close!

**Comment by Milaine** [comment]
Could you give me an code example with a command that triggers an reaction?
That's the part I understand the least.

Why do I have to subscribe the event and use a placeholder?

the part with e was already understood by looking at the code *proud* :3

What about the `UpdateReceived`? Isn't every message an update?

**Comment by MrRoundRobin** [comment]
with UpdateReceived you get all Updates. the others are only shorthands

**Comment by MrRoundRobin** [comment]
related to #83, should be fixed in f8ebeaf85e76dec965e1f6e74687341af8a292ba

**Comment by Milaine** [comment]
wtf man, there is a dozen other questions I asked and you just closed the issue

**Comment by MrRoundRobin** [comment]
sorry mixed up, it's to late

**Comment by guitarxhero** [comment]
It's all okay!

So, you don't need to worry about what triggers the reactions, the library does that automatically.

Why to subscribe an event? Some reasons:
- You can subscribe the MessageReceived event to multiple delegates
- ..I was going to type something I forgot -- Distracted
But the reason you'd want to hear is: 
-  You want to do something when you get something (in this case: a message)

Example:
You get a gift on christmas, you didn't generate the event where someone gives you a present. You can do anything with that gift, that gift is `e` (which you understand).

**Comment by Milaine** [comment]
ah so basically it has the advantage that Client_MessageReceived can be triggered by multiple Bot.thingy things once I set it up that way?

So how do I make simple commands like /hi -> [output] hello?

**Comment by guitarxhero** [comment]
Yes! Or an event subscribed/attached to multiple delegates (yes, they're called like that)

And simple, you can start with the following code if you wish:

```csharp
static void Client_MessageReceived(object sender, MessageEventArgs e)
{
    switch(e.Message.Text)
    {
        case "/hello":
        case "/start": // Telegram bots starting command
            Service.SendTextMessage(e.Message.Chat.Id, "Hello~!");
            break;
            
        case "/killme":
            Service.SendTextMessage(e.Message.Chat.Id, "I'd never to that!");
            break;
        
        default:
            Service.SendTextMessage(e.Message.Chat.Id, "Invalid command~!");
            break;
    }
}
```

I'm sure you'll understand the structure!

**Comment by Milaine** [comment]
ah, so the cases are basically only dividing it into either text, phot [...] messages?
I did that too but inside the last switch.

Last question I have is, does this system fully replace the system I had or is there some programming magic in my code I don't even know about?

**Comment by guitarxhero** [comment]
Yep!

My proposal will entirely, indeed, replace your setup.

I previously tried similar to your system, that is manually fetching the updates and keeping up with the Update IDs. I dropped that once I notice the library has events (which is a nice thing because then I implemented a command line system for my bot. Screenshot because why not: 
![image](https://cloud.githubusercontent.com/assets/8390674/13267654/749eb146-da4c-11e5-8d6a-7e664eee6d6a.png))


Curiosity inbound, are you rather new to programming and/or C#? Either way, if you wish, you can send me an email and I'll reply with my Skype username, Steam, or anything else!

**Comment by Milaine** [comment]
It's good to know that :3
Thank you for all the help, and yeah, I'm kinda new to programming, I only had some Java in school for 1.5 years now and in the beginning I learned a bit of C# aswell, now that I wanted to make a bot and the java solutions I found were horrible I searched for C# and it was simple enough to understand :3 all my programming knowledge is just transferred from java since the languages are so similar.

**Comment by guitarxhero** [comment]
Glad to be of help. :3

**Comment by Milaine** [comment]
Turns out it doesn't work at all :I


  ```
 static api Bot;
        static void Main(string[] args)
        {   
            Bot = new Telegram.Bot.Api("116800441:AAEN11IcsivuMEwIcPanHbhnOlP00inE2CE");
            var me = await Bot.GetMe();
            Console.WriteLine("Hello my name is {0}", me.Username);
            Bot.MessageReceived += Client_MessageReceived;
            Bot.StartReceiving();
            Console.ReadLine();
        }
        static void Client_MessageReceived(object sender, MessageEventArgs User)
        {
            switch (User.Message.Text)
            {
                case "/qt": 
                    Bot.SendTextMessage(User.Message.Chat.Id, "Hello~!");
                    break;
            }
        }
```

Any idea what I did wrong?

**Comment by guitarxhero** [comment]
Try replacing `var me = await Bot.GetMe();` to `var me = Bot.GetMe().Result`.

Everything else seems fine to me.

**Comment by Milaine** [comment]
that part is unrelated to the functionality of the bot I think, I removed it completely and it didnt help.

What about the `MessageEventArgs User` and the `object sender` aswell as the `User.Message.Text`?
it all looks very different from my code

**Comment by guitarxhero** [comment]
What are the errors (if any)?

I just noticed in `static api Bot;`, `api` must be capitalized as `Api` like so:
```csharp
using System;
using Telegram.Bot;
using Telegram.Bot.Types;

namespace TelegramBotTest
{
    class Program
    {
        static Api Bot;
        static void Main(string[] args)
        {
            Bot = new Api("116800441:AAEN11IcsivuMEwIcPanHbhnOlP00inE2CE");
            Bot.MessageReceived += Client_MessageReceived;
            Bot.StartReceiving();
            Console.ReadLine();
        }
        static void Client_MessageReceived(object sender, MessageEventArgs User)
        {
            switch (User.Message.Text)
            {
                case "/qt":
                    Bot.SendTextMessage(User.Message.Chat.Id, "Hello~!");
                    break;
            }
        }
    }
}
```

I even get a reply with my own bot (and own API key).

**Comment by Milaine** [comment]
Okay, so I just placed the whole code in a new file in a new project,
 changed `static api Bot;` to `static Telegram.Bot.Api Bot;`
and removed
 `var me = await Bot.GetMe(); 
Console.WriteLine("Hello my name is {0}", me.Username);`
because VS said I had to make it async in order to work and I have zero idea what that even is even through I got that word thrown in my face since I started using this library.

AAAnd while I am typing it crashed again.

I researched mscorlib.dll and as it turns out, a file named "microsoft core library" is kinda essential.
either I am writing pretty bad code or my system is corrupted.

could you try and check if it works for you?

```
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Telegram.Bot.Types;
using File = System.IO.File;

using System.Net;

namespace TBOT3
{
    class Program
    {
        // static api Bot;
        static Telegram.Bot.Api Bot;
        static void Main(string[] args)
        {
            Bot = new Telegram.Bot.Api("Your Token Here");

           // var me = await Bot.GetMe();

           // Console.WriteLine("Hello my name is {0}", me.Username);

            Bot.MessageReceived += Client_MessageReceived;

            Bot.StartReceiving();
            Console.ReadLine();
        }
        static void Client_MessageReceived(object sender, MessageEventArgs User)
        {
            switch (User.Message.Text)
            {
                case "/qt":
                    Bot.SendTextMessage(User.Message.Chat.Id, "Hello~!");
                    break;
            }
        }
}
}
}
```

**Comment by guitarxhero** [comment]
It works when I remove the last brace (`}`).

I'm using .NET 4.5.2 with Visual Studio 2015 Community.

Here are my project files. Remember to change the token!

[TelegramBotTest.zip](https://github.com/MrRoundRobin/telegram.bot/files/143609/TelegramBotTest.zip)

..Finished writing this and my bot (main) crashed. Assuming it's the library.

**Comment by MrRoundRobin** [comment]
You need to use [async/await](https://msdn.microsoft.com/en-us/library/hh191443.aspx) 

So `Bot.Send... ` Needs to be `async Bot.Send....` Or `Bot.Send..(....).Result`

**Comment by guitarxhero** [comment]
My bot wasn't even sending anything, which is odd.

I'll still update it using `async`.

**Comment by guitarxhero** [comment]
Oh wow silly me, NuGet package update. (8.0 to 8.1)

**Comment by Milaine** [comment]
wait
wat
what am I supposed to do

**Comment by guitarxhero** [comment]
@MrRoundRobin 
I have no luck with `await` nor `async`.

e.g.
`Message t = await Service.SendPhoto(pChat.Id, new FileToSend(f, Open(f, FileMode.Open))).Result;` 
Getting `CS4033` and `CS1061` errors

"`'Message' does not contain a definition for 'GetAwaiter' and no extension method 'GetAwaiter' accepting a first argument of type 'Message' could be found (are you missing a using directive or an assembly reference?`" (Tried referencing everything as well)

while
`Service.SendPhoto(pChat.Id, new FileToSend(f, Open(f, FileMode.Open)));`
always worked for me.

@Milaine 
Have you tried my project files? I tested it and it worked fine for me.

**Comment by guitarxhero** [comment]
`await Service.SendPhoto(pChat.Id, new FileToSend(f, Open(f, FileMode.Open)));` works when the method is defined with async tho

**Comment by Milaine** [comment]
Didn't it crash for you?
Did you change something?
I can't really see throught the stuff you're talking about uvu

**Comment by guitarxhero** [comment]
Didn't crash again since last time.

Sorry though -- the author recommended me using an asynchronous (intermediate stuff) model. Like so (example):
```csharp
static async void SendText(Message pMessage)
{
    await Service.SendPhoto(pMessage.Chat.Id, "Hi");
}
```

**Comment by cnokobe** [comment]
About the first comment - try to put System.Threading.Thread.Sleep(1) in the end of the while loop.

**Comment by Milaine** [comment]
about that code example:
could you give me a context to this?
Looks a bit confusing since you write `SendText` at the top and in the thing you write `SendPhoto`

**Comment by guitarxhero** [comment]
oh oops, my mistake, I meat `SendText`

**Comment by Milaine** [comment]
and could you show me a code sample with some more context please?
I am not fully sure if I understand this right

**Comment by guitarxhero** [comment]
Does this help you?

```csharp
// This is a delegate, which we subcribed it to the MessageReceived event earlier
static void Client_MessageReceived(object sender, MessageEventArgs e)
{
    switch (e.Message.Text) // Depending on the text..
    {
        // .. if it's "/start"
        case "/start":
            // Send a message to the chat id (basically, the group chat or user chat)
            await Service.SendText(e.Message.Chat.Id, "Hello!");
            break;
            
        // .. if it's anything else
        default:
            await Service.SendText(e.Message.Chat.Id, "Unknown command!");
            break;
    }
}
```

Also my bot's uptime is 20 hours so wew

**Comment by Milaine** [comment]
but what about this async stuff now?

**Comment by guitarxhero** [comment]
Basically, a program goes A to B to C. If B is a heavy task, the program will freeze and complete B before going to C.

You could put B in another thread, use `BackgroundWorker`, or use **async**hronous methods to put aside the task B while the main thread goes back to C. So B and C are both executing at the same time.

It's very useful for UI projects.

> With async and await, we formalize and clarify how asynchronous, non-blocking methods begin and end. An async method can return only void or a Task.

http://www.dotnetperls.com/async

**Comment by Milaine** [comment]
Okay, so I just translated the picture logger which I deemed to be the most difficult thing into the new scheme and it seems to work great!
```
static async void Client_MessageReceived(object sender, MessageEventArgs User)
        {
            switch (User.Message.Text)
            {
                case "/qt":
                    await Bot.SendTextMessage(User.Message.Chat.Id, "Hello~!");
                    break;
            }
            if (User.Message.Type == MessageType.PhotoMessage)
            {
                var file = await Bot.GetFile(User.Message.Photo.LastOrDefault().FileId);

                Console.WriteLine("Received Photo: {0}", file.FilePath);
                Console.WriteLine("File id is: {0}", file.FileId);
                System.IO.File.WriteAllText(@"D:\FILEID.txt", file.FileId + "\n");
                // await Bot.SendPhoto(message.Chat.Id, file.FileId);
            }
        }
```

Thank you for this new concept, I'm currently running it, waiting for an error report to come up, if there's none I'll close this I guess, but I think it's actually not code related but rather some other issue of the software...

**Comment by Milaine** [comment]
I had a second file in the project which may had led to this error, I'm not sure tho.
HOWEVER, the Problem is now solved and my bot looks pretty much better than before, thank you Guys a lot for you help :3 <3~

**Comment by guitarxhero** [comment]
:heart:
