### ISSUE TITLE
Silent Message support

### ISSUE THREAD

**Issue by MrRoundRobin** [MrRoundRobin/telegram.bot#98]
https://telegram.org/blog/channels-2-0#silent-messages

> iOS users will not receive a notification, Android users will receive a notification with no sound. Other apps coming soon.

**Comment by Bouki6** [comment]
Hello.
apparently telegram add optional parameters disable notification to its methods. would you please tell us when you are gonna add it to your library?
Thank you.

**Comment by MrRoundRobin** [comment]
should be done, uploading new package to nuget in a few minutes
