### ISSUE TITLE
"System.NullReferenceException" in /echo command

### ISSUE THREAD

**Issue by Milaine** [MrRoundRobin/telegram.bot#99]
hi, so I have this code in an action listener (static async void):
```
switch (User.Message.Text)
            {
                case "/qt":
                    await Bot.SendTextMessage(User.Message.Chat.Id, "Hello~!");
                    break;            
            }

            if (User.Message.Text.Contains("/echo"))
            {
                string echo = User.Message.Text.Replace(@"/echo", "");
                await Bot.SendTextMessage(User.Message.Chat.Id, echo);
            }
```
and after starting my bot I get this error.
At first I had the if statement placed above the switch and then I placed it below which seemed like it'd fix it but now it happens all the time again when I try to start the bot.

My theory is that there may be an error with the variables but since I have no experience with VS error codes I really don't know.

Had this for a while now and in my previous configuration it worked

**Comment by cnokobe** [comment]
Just put breakpoints, debug, and see what's null. Probably Message.Text is null if the message you are handling is not text (picture message or something).

**Comment by Milaine** [comment]
ah thank you, that was wrong, fixed it.
Now I got an error that my /echo string was empfy and I solved that
and added an "else" for whenever an command doesn't work, but got an error "bot was blocked by user"

So.. how do I code it so that in case the bot is blocked it doesn't crash?

**Comment by Bouki6** [comment]
you should handle the errors. something like this:
```
            try
            {
                var task = new Api("bot token").SendTextMessage(66617958, "Test Message");
                if (await Task.WhenAny(task, Task.Delay(1000)) == task)
                {
                    var message = await task;
                    MessageBox.Show(JsonConvert.SerializeObject(message));
                }
                else
                {
                    MessageBox.Show(JsonConvert.SerializeObject("time out"));
                }
            }
            catch (ApiRequestException ex)
            {
                MessageBox.Show(ex.Message.ToString());
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message.ToString());
           
``` }

**Comment by Milaine** [comment]
thanks alot! It works great :3
I hope I now have all the basics together :3
